action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_bubble() ]]]'  ## 引用全局函数【theme_bubble()】style样式
    content:
      type: vertical-stack
      cards: 
        - type: custom:bubble-card
          card_type: button
          button_type: name
          name: "主卧房间"
          icon: "mdi:bed-king"
          card_layout: large
          sub_button:
            - entity: "sensor.wendu_zhuwo"
              show_state: true
              show_background: false
              show_icon: true
            - entity: "sensor.shidu_zhuwo"
              show_state: true
              state_background: false
              show_background: false
            - entity: "sensor.jinghuaqi_zhuwo_pm25"
              show_state: true
              state_background: false
              show_background: false
          styles: ""
        - type: custom:bubble-card
          card_type: separator
          name: ""
        - type: horizontal-stack
          cards:
            - type: custom:bubble-card
              card_type: button
              button_type: state
              entity: "light.zhuwodeng"
              tap_action:
                action: "toggle"
              button_action:
                tap_action:
                  action: "toggle"
              card_layout: "large-2-rows"
              styles: "ha-card {.bubble-button-background {\n   background-color: ${state === 'on' ? 'rgb(250,105,50)' : ''} ;\n}\n.bubble-icon {\n   color: ${state === 'on' ? 'rgb(250,105,50)' : ''} !important;\n}"
            - type: custom:bubble-card
              card_type: button
              button_type: state
              entity: "light.zhuwomentingdeng"
              tap_action:
                action: "toggle"
              button_action:
                tap_action:
                  action: "toggle"
              card_layout: "large-2-rows"
              styles: "ha-card {.bubble-button-background {\n   background-color: ${state === 'on' ? 'rgb(250,105,50)' : ''} ;\n}\n.bubble-icon {\n   color: ${state === 'on' ? 'rgb(250,105,50)' : ''} !important;\n}"
        - type: custom:bubble-card
          card_type: button
          button_type: slider
          entity: "light.taideng"
          tap_action:
            action: "toggle"
          button_action:
            tap_action:
              action: "toggle"
          card_layout: "large-2-rows"
          scrolling_effect: true
          sub_button:
            - entity: "light.taideng"
              show_name: false
              show_icon: false
              show_background: false
              show_attribute: true
              attribute: "brightness"
            - entity: "light.taideng"
              show_name: false
              show_icon: false
              show_background: false
              show_attribute: true
              attribute: "color_temp_kelvin"
          show_state: true
        - type: custom:bubble-card
          card_type: separator
        - type: custom:bubble-card
          card_type: climate
          entity: "climate.kongtiao_zhuwo"
          sub_button:
            - entity: "climate.kongtiao_zhuwo"
              select_attribute: "hvac_modes"
              show_arrow: false
          card_layout: large
          scrolling_effect: true
          show_icon: true
          force_icon: false
          show_state: true
          show_last_changed: false
          show_attribute: false
          state_color: true
        - type: custom:bubble-card
          card_type: climate
          entity: "climate.shuinuantan"
          sub_button:
            - name: "HVAC modes menu"
              select_attribute: "hvac_modes"
              state_background: false
              show_arrow: false
          card_layout: large
          force_icon: false
          show_state: true
          state_color: true
        - type: custom:bubble-card
          card_type: button
          entity: "fan.jinghuaqi_zhuwo"
          show_state: true
          show_attribute: false
          attribute: "supported_features"
          tap_action:
            action: "toggle"
          button_action:
            tap_action:
              action: "toggle"
          sub_button:
            - entity: "sensor.jinghuaqi_zhuwo_pm25"
              show_icon: false
              show_background: false
              show_state: true
            - entity: "select.jinghuaqi_zhuwo"
              show_icon: false
              show_background: true
              show_state: true
          card_layout: large
          styles: "ha-card {\n  --bubble-select-list-item-accent-color: ${state === 'on' ? 'rgb(50,205,50)' : ''} ;\n}\n.bubble-button-background {\n   background-color: ${state === 'on' ? 'rgb(50,205,50)' : ''} ;\n}\n.bubble-icon {\n   color: ${state === 'on' ? 'rgb(50,205,50)' : ''} !important;\n}"
        - type: custom:bubble-card
          card_type: button
          entity: "humidifier.jiashiqi_zhuwo"
          card_layout: large
          tap_action:
            action: "toggle"
          button_action:
            tap_action:
              action: "toggle"
          sub_button:
            - entity: "humidifier.jiashiqi_zhuwo"
              show_attribute: true
              attribute: "current_humidity"
              show_background: false
              show_icon: false
            - entity: "select.jiashiqi_zhuwo"
              show_state: true
              state_background: true
              show_arrow: true
          show_state: true
          show_attribute: false
          icon: "mdi:air-humidifier"
          styles: "ha-card {\n  --bubble-select-list-item-accent-color: ${state === 'on' ? 'rgb(30,144,255)' : ''} ;\n}\n.bubble-button-background {\n   background-color: ${state === 'on' ? 'rgb(30,144,255)' : ''} ;\n}\n.bubble-icon {\n   color: ${state === 'on' ? 'rgb(30,144,255)' : ''} !important;\n}"
        - type: custom:bubble-card
          card_type: separator
          name: ""
        - type: custom:bubble-card
          card_type: media-player
          entity: "media_player.xiaomiyinxiang"
          card_layout: large
          show_state: true
          cover_background: true
        - type: custom:bubble-card
          card_type: separator
          name: ""


 