action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_bubble() ]]]'  ## 引用全局函数【theme_bubble()】style样式
    content:
      type: vertical-stack
      cards: 
        - type: custom:bubble-card
          card_type: button
          button_type: name
          name: "餐厅房间"
          icon: "mdi:silverware-fork-knife"
          card_layout: large
          sub_button:
            - entity: "sensor.wendu_keting"
              show_state: true
              show_background: false
              show_icon: true
            - entity: "sensor.shidu_keting"
              show_state: true
              state_background: false
              show_background: false
        - type: custom:bubble-card
          card_type: separator
        - type: horizontal-stack
          cards:
            - type: custom:bubble-card
              card_type: button
              button_type: state
              entity: "light.cantingdeng"
              tap_action:
                action: "toggle"
              button_action:
                tap_action:
                  action: "toggle"
              card_layout: "large-2-rows"
              name: ""
              styles: ".bubble-button-background {\nbackground-color: ${state === 'on' ? 'rgb(250,105,50)' : ''} ;\n}\n.bubble-icon {\ncolor: ${state === 'on' ? 'rgb(250,105,50)' : ''} !important;\n}"
            - type: custom:bubble-card
              card_type: button
              button_type: state
              entity: "light.cantingtongdeng"
              tap_action:
                action: "toggle"
              button_action:
                tap_action:
                  action: "toggle"
              card_layout: "large-2-rows"
              styles: ".bubble-button-background {\nbackground-color: ${state === 'on' ? 'rgb(250,105,50)' : ''} ;\n}\n.bubble-icon {\ncolor: ${state === 'on' ? 'rgb(250,105,50)' : ''} !important;\n}"
        - type: custom:bubble-card
          card_type: separator
        - type: custom:bubble-card
          card_type: climate
          sub_button:
            - entity: "climate.kongtiao_keting"
              select_attribute: "hvac_modes"
              show_arrow: false
          card_layout: large
          scrolling_effect: true
          show_icon: true
          force_icon: false
          show_state: true
          show_last_changed: false
          show_attribute: false
          state_color: true
          entity: "climate.dinuan"
        - type: custom:bubble-card
          card_type: button
          entity: "vacuum.saodijiqiren"
          card_layout: large
          show_state: true
          show_attribute: "true"
          attribute: "battery_level"
          sub_button:
            - name: "Return to dock"
              icon: "mdi:home"
              show_background: false
              tap_action:
                action: "call-service"
                service: "vacuum.return_to_base"
                target:
                  entity_id: "vacuum.downstairs"
            - name: "Pause"
              icon: "mdi:pause"
              show_background: false
              tap_action:
                action: "call-service"
                service: "vacuum.pause"
                target:
                  entity_id: "vacuum.downstairs"
            - name: "Start"
              icon: "mdi:play"
              tap_action:
                action: "call-service"
                service: "vacuum.start"
                target:
                  entity_id: "vacuum.downstairs"
            - entity: "select.dreame_cn_1023400391_p2140_mode_p_2_3"
              show_state: true
        - type: custom:bubble-card
          card_type: button
          entity: "冰箱"
          show_state: true
          show_attribute: false
          attribute: "supported_features"
          tap_action:
            action: "toggle"
          button_action:
            tap_action:
              action: "toggle"
          sub_button:
            - entity: "sensor.refrigerator_temp_right"
              show_state: true
              state_background: false
              show_background: false
              show_icon: false
              show_name: true
              name: "冷藏室"
            - entity: "sensor.refrigerator_temp_left"
              show_state: true
              show_name: true
              show_icon: false
              state_background: true
              name: "冷冻室"
              show_background: false
          card_layout: "large-2-rows"
          icon: "mdi:fridge"
          name: "冰箱"
          force_icon: false
          button_type: "name"
        - type: custom:bubble-card
          card_type: separator
        - type: custom:button-card
          styles:
            card:
              - background: "rgb(0,0,0,0)"
              - height: "120px"
              - padding: "0"
              - border-width: "0"
          


