action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_bubble() ]]]'  ## 引用全局函数【theme_bubble()】style样式
    content:
      type: vertical-stack
      cards: 
        - type: custom:bubble-card
          card_type: button
          button_type: name
          name: "次卧房间"
          icon: "mdi:bed-king"
          card_layout: large
          sub_button:
            - entity: "sensor.wendu_ciwo"
              show_state: true
              show_background: false
              show_icon: true
            - entity: "sensor.shidu_ciwo"
              show_state: true
              state_background: false
              show_background: false
        - type: custom:bubble-card
          card_type: separator
        - type: custom:bubble-card
          card_type: button
          button_type: state
          entity: "light.ciwodeng"
          tap_action:
            action: "toggle"
          button_action:
            tap_action:
              action: "toggle"
          card_layout: "large-2-rows"
          name: ""
          styles: ".bubble-button-background {\nbackground-color: ${state === 'on' ? 'rgb(250,105,50)' : ''} ;\n}\n.bubble-icon {\ncolor: ${state === 'on' ? 'rgb(250,105,50)' : ''} !important;\n}"
        - type: custom:bubble-card
          card_type: separator
          


