冰箱: 
  show_label: true
  label: |
    [[[
        var a = states[variables.冷藏门状态]?.state === "off" ? "已关闭" : "已打开";
        var b = states[variables.冷冻门状态]?.state === "off" ? "已关闭" : "已打开";
        return "冷藏门：" + a + "&emsp;&emsp;&emsp;冷冻门：" + b;
    ]]]
  styles: 
    label:
      - font-size: 13px
      - color: |
          [[[ 
            var a = states[variables.冷藏门状态]?.state === "off" ? "已关闭" : "已打开";
            var b = states[variables.冷冻门状态]?.state === "off" ? "已关闭" : "已打开";
            if (a=="已打开" || b=="已打开") return "rgb(0,200,200)";
            return variables.主题=="on" ? "rgb(0,0,0)" : "rgb(255,255,255)";
          ]]]
    card:
      - padding: 1% 0 1% 0
      - width: 400px
      - height: 59px
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题=="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'

冰箱图表: 
  styles: 
    grid:
      - grid-template-areas: |
          "图表"
      - grid-template-columns: 100%
      - grid-template-rows: 100%
    card:  
      - padding: 0
      - width: 400px
      - height: 260px
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题=="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
  custom_fields:
    图表:
      card:
        type: custom:apexcharts-card
        card_mod:  
          style: '[[[ return theme_apexcharts()]]]'
        header:
          show: true
          show_states: true
          colorize_states: true
          standard_format: true
        graph_span: 15m 
        apex_config:
          grid:
            position: front
            row:
              colors:
                - black
                - transparent
              opacity: 0.1
            xaxis:
              lines:
                show: false
            yaxis:
              lines:
                show: false
          chart:
            height: 200 
        now:
          show: true
          color: "#80a4ff"
          label: 现在
        series:   
          - entity: '[[[ return variables.实际温度 ]]]'
            name: '[[[ return variables.实际温度名称 ]]]'
            unit: "℃" 
            type: area
            fill_raw: last
            stroke_width: 1   
          - entity: '[[[ return variables.设定温度 ]]]'
            name: '[[[ return variables.设定温度名称 ]]]'
            unit: "℃" 
            fill_raw: last
            stroke_width: 1   

