地暖:
  triggers_update:
    - '[[[ return variables.地暖 ]]]'
    - '[[[ return variables.附加信息 ]]]'
  styles:
    grid:
      - grid-template-areas: |
          [[[
             if (variables.附加信息=='左侧')  return '"mo b b  b  b  b  b  b  b"' +
                                                    '"mo y a0 a0 a0 a0 a0 a0 x"' +
                                                    '"mo y i2 i2 i2 i2 i2 i2 x"' +
                                                    '"mo y i3 i3 i3 i3 i3 i3 x"' +
                                                    '"mo y i4 i4 i4 i4 i4 i4 x"' +
                                                    '"mo y z5 m  m  p  p  z6 x"' +
                                                    '"mo y a1 a1 a1 a2 a2 a2 x"' +
                                                    '"mo y a3 a3 a4 a4 a5 a5 x"' ;
             if (variables.附加信息=='右侧')  return '"b b  b  b  b  b  b  b mo"' +
                                                    '"y a0 a0 a0 a0 a0 a0 x mo"' +
                                                    '"y i2 i2 i2 i2 i2 i2 x mo"' +
                                                    '"y i3 i3 i3 i3 i3 i3 x mo"' +
                                                    '"y i4 i4 i4 i4 i4 i4 x mo"' +
                                                    '"y z5 m  m  p  p  z6 x mo"' +
                                                    '"y a1 a1 a1 a2 a2 a2 x mo"' +
                                                    '"y a3 a3 a4 a4 a5 a5 x mo"' ;
             else return  '"b b  b  b  b  b  b  b"' +
                          '"y a0 a0 a0 a0 a0 a0 x"' +
                          '"y i2 i2 i2 i2 i2 i2 x"' +
                          '"y i3 i3 i3 i3 i3 i3 x"' +
                          '"y i4 i4 i4 i4 i4 i4 x"' +
                          '"y z5 m  m  p  p  z6 x"' +
                          '"y a1 a1 a1 a2 a2 a2 x"' +
                          '"y a3 a3 a4 a4 a5 a5 x"' ;
          ]]]
      - grid-template-columns: |
          [[[
             if (variables.附加信息=='左侧')  return "67px 18px 44px 44px 44px 44px 44px 44px 18px";
             if (variables.附加信息=='右侧')  return "18px 44px 44px 44px 44px 44px 44px 25px 67px";
             return "18px 44px 44px 44px 44px 44px 44px 18px";
          ]]]
      - grid-template-rows: 0px 340px 0px 0px 0px 0px 0px 0px 0px 0px
    card:
      - padding: 0
      - width: |
          [[[
              if (variables.附加信息=='左侧' || variables.附加信息=='右侧') return "370px";
              return "300px";
          ]]]
      - height: 455px
      - border-width: 0
      - background: transparent
  custom_fields:
    b:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 455px
            - width: 300px
            - height: 455px
            - border-radius: 15px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
    i2:
      card:
        type: custom:button-card
        styles: 
          card:
            - margin-top: -272px
            - border-width: 0
            - background: |
                [[[ 
                    var state = states[variables.地暖].state;
                    if(state=='auto' ) return "radial-gradient(rgb(255,69,0) -20%, transparent 50%)" ;
                    return "transparent" ;
                ]]]
            - width: 264px
            - height: 264px
    a0:
      card: 
        type: thermostat
        entity: '[[[ return  variables.地暖 ]]]'
        card_mod:
          style: |
            [[[ 
                const label_on = `
                  ha-card{ 
                    background: rgb(0,0,0,0); 
                    border-width: 0;
                    color: rgb(0,0,0);
                    --disabled-color: rgb(120,120,120);
                    --state-climate-auto-color: rgb(255,69,0);
                    --state-active-color: rgb(202,165,0);
                  }
                `;   
                const label_off = ` 
                  ha-card{ 
                    background: rgb(0,0,0,0);
                    border-width: 0;
                    color: rgb(255,255,255);
                    --disabled-color: rgb(220,220,220);
                    --state-climate-auto-color: rgb(255,69,0);
                    --state-active-color: rgb(202,165,0);
                  }
                `; 
                return variables.主题 =="on"  ? label_on : label_off; 
            ]]]
    i3:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 40px
            - width: 264px
            - height: 42px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'
            - border-radius: 10px
    i4:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 150px
            - width: 264px
            - height: 42px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'
            - border-radius: 10px
    m:
      card:
        type: custom:button-card
        entity: '[[[ return  variables.地暖 ]]]'
        show_icon: true
        show_name: false
        show_state: false
        icon: 'mdi:minus'
        styles:
          card:
            - margin-top: -75px
            - width: 50px
            - height: 50px
            - border-radius: 25px
            - border: '[[[ return variables.主题 =="on" ? "2px solid rgb(150,150,150)" : "2px solid rgb(180,180,180)" ]]]'
            - margin-left: '27px'
            - --mdc-ripple-color: white
            - --mdc-ripple-press-opacity: 0.3
            - background: rgb(0,0,0,0)
          icon:
            - width: 25px
            - height: 25px
            - color: '[[[ return variables.主题 =="on" ? "rgb(150,150,150)" : "rgb(180,180,180)"; ]]]'
        tap_action:
          action: call-service
          service: climate.set_temperature
          data:
            temperature: '[[[ return states[variables.地暖].attributes.temperature-1 ]]]'
          target:
            entity_id: '[[[ return  variables.地暖 ]]]'
    p:
      card:
        type: custom:button-card
        entity: '[[[ return  variables.地暖 ]]]'
        show_icon: true
        show_name: false
        show_state: false
        icon: 'mdi:plus'
        styles:
          card:
            - margin-top: -75px
            - width: 50px
            - height: 50px
            - border-radius: 25px
            - border: '[[[ return variables.主题 =="on" ? "2px solid rgb(150,150,150)" : "2px solid rgb(180,180,180)" ]]]'
            - margin-left: '12px'
            - --mdc-ripple-color: white
            - --mdc-ripple-press-opacity: 0.3 
            - background: rgb(0,0,0,0)
          icon:
            - width: 25px
            - height: 25px
            - color: '[[[ return variables.主题 =="on" ? "rgb(150,150,150)" : "rgb(180,180,180)"; ]]]'
        tap_action:
          action: call-service
          service: climate.set_temperature
          data:
            temperature: '[[[ return states[variables.地暖].attributes.temperature-(-1) ]]]'
          target:
            entity_id: '[[[ return  variables.地暖 ]]]'
    a1:
      card:
        type: custom:button-card
        show_icon: true
        icon: mdi:fire
        styles:
          card:
            - margin-top: 40px
            - width: 132px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: |
                [[[ 
                    var state = states[variables.地暖].state;
                    if(state=='auto' ) return "rgb(255,69,0)";
                    return "rgb(0,0,0,0)";
                ]]]
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 
        tap_action:
          action: call-service
          service: climate.set_hvac_mode
          data:
            hvac_mode: auto
          target:
            entity_id: '[[[ return  variables.地暖 ]]]'
    a2:
      card:
        type: custom:button-card
        show_icon: true
        icon: mdi:power
        styles:
          card:
            - margin-top: 40px
            - width: 132px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: |
                [[[
                    var state = states[variables.地暖].state;
                    if(state=='auto' ) return "rgb(0,0,0,0)";
                    if(state=='off') return variables.主题 =="on" ? "rgb(180,180,180)" : "rgb(150,150,150)"
                    return "rgb(0,0,0,0)";
                ]]]
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 
        tap_action:
          action: call-service
          service: climate.set_hvac_mode
          data:
            hvac_mode: "off"
          target:
            entity_id: '[[[ return  variables.地暖 ]]]'
    a3:
      card:
        type: custom:button-card
        show_icon: true
        show_label: true
        label: 防冻
        icon: mdi:snowflake-alert
        styles:
          card:
            - margin-top: 150px
            - width: 88px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: transparent
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 
            - font-size: 11px
    a4:
      card:
        type: custom:button-card
        show_icon: true
        show_label: true
        label: 舒适
        icon: mdi:thermostat-auto
        styles: 
          card:
            - margin-top: 150px
            - width: 88px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: transparent
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'  
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 
            - font-size: 11px
    a5:
      card:
        type: custom:button-card
        show_icon: true
        show_label: true
        label: 周计划
        icon: mdi:calendar-week
        styles:
          card:
            - margin-top: 150px
            - width: 88px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: transparent
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'  
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 
            - font-size: 11px       
    mo:
      card:
        type: custom:button-card
        styles:
          grid:
            - grid-template-areas: |
                'b1' 'b2' 'b3'
            - grid-template-columns: 60px
            - grid-template-rows: 0px 0px 0px
          card:
            - padding: 0
            - margin-top: 115px
            - width: 60px
            - height: 455px
            - border-radius: 15px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
        custom_fields:
          b1:
            card:
              type: custom:button-card
              icon: mdi:fire-off
              show_icon: true
              show_label: true
              label: 停止
              styles:
                card:
                  - margin-top: 610px
                  - margin-left: 8px
                  - border-radius: 10px
                  - width: 42px
                  - height: 42px
                  - border-width: 0
                  - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'  
                label:
                  - font-size: 11px
                  - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
                icon:
                  - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 
          b2:
            card:
              type: custom:button-card
              icon: mdi:fire
              show_icon: true
              show_label: true
              label: 暂停
              styles:
                card:
                  - margin-top: 720px
                  - margin-left: 8px
                  - border-radius: 10px
                  - width: 42px
                  - height: 42px
                  - border-width: 0
                  - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'  
                label:
                  - font-size: 11px
                  - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
                icon:
                  - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 
          b3:
            card:
              type: custom:button-card
              icon: mdi:fire
              show_icon: true
              show_label: true
              label: 启动
              styles:
                card:
                  - margin-top: 830px
                  - margin-left: 8px
                  - border-radius: 10px
                  - width: 42px
                  - height: 42px
                  - border-width: 0
                  - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'  
                label:
                  - font-size: 11px
                  - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
                icon:
                  - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]' 