浴霸:
  triggers_update:
    - '[[[ return variables.浴霸 ]]]'
    - '[[[ return variables.吹风 ]]]'
    - '[[[ return variables.换气 ]]]'
    - '[[[ return variables.取暖 ]]]'
    - '[[[ return variables.温度 ]]]'
  styles:
    grid:
      - grid-template-areas: |
          'b b  b  b  b  b  b  b' 
          'y i1 i1 i1 i1 i1 i1 x' 
          'y i2 i2 i2 i2 i2 i2 x' 
          'y i3 i3 i3 i3 i3 i3 x' 
          'y i4 i4 i4 i4 i4 i4 x'
          'y z0 n  n  n  n  z1 x' 
          'y z2 z2 l1 l1 z3 z3 x' 
          'y z2 z2 s  s  z4 z4 x' 
          'y z2 z2 s  s  u  z5 x' 
          'y z6 l2 l2 l2 l2 z5 x' 
          'y z6 m  m  p  p  z5 x' 
          'y a1 a1 a2 a2 a3 a3 x' 
          'y a4 a4 a5 a5 a6 a6 x'  
      - grid-template-columns: 18px 44px 44px 44px 44px 44px 44px 18px
      - grid-template-rows: 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px
    card:
      - padding: 0
      - width: 300px
      - height: 455px
      - border-width: 0
      - background: rgb(0,0,0,0)
  custom_fields:
    b:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 455px
            - width: 300px
            - height: 455px
            - border-radius: 15px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
    i1:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 428px
            - border-width: 0
            - background: |
                [[[ 
                    var vent = states[variables.换气].state;  
                    var blow = states[variables.吹风].state;   
                    var heat = states[variables.取暖].state;   
                    if(vent=='on'  && blow=='on'  && heat=='on')  return "rgb(254,111,33)";
                    if(vent=='on'  && blow=='on'  && heat=='off') return "rgb(33,150,243)";
                    if(vent=='on'  && blow=='off' && heat=='off') return "rgb(0,188,213)";
                    if(vent=='off' && blow=='on'  && heat=='on')  return "rgb(254,111,33)";
                    if(vent=='off' && blow=='on'  && heat=='off') return "rgb(33,150,243)";
                    return variables.主题 =="on" ? "rgb(200,200,200)" : "rgb(100,100,100)";
                ]]]
            - width: 300px
            - height: 264px
            - margin-left: 10px
            - clip-path: >-
                path('M224.1,121.4c0-1.8,0.1-3.5,0-5.3c-0.2-2.8-0.4-5.6-0.8-8.3c-0.6-4.4-1.5-8.8-2.6-13.1
                c-1.1-4.3-2.6-8.5-4.3-12.6c-2.4-5.9-5.3-11.5-8.8-16.8c-2.6-4-5.4-7.8-8.6-11.3c-2.2-2.5-4.4-4.9-6.8-7.2
                c-5.4-5.1-11.3-9.7-17.7-13.5c-6.4-3.8-13.1-7-20.2-9.4c-5.2-1.7-10.4-3-15.8-4c-2.4-0.4-4.8-0.7-7.2-1c-1-0.1-2.1-0.2-3.1-0.2
                c-3.2-0.2-6.5-0.5-9.7-0.2c-3.3,0.2-6.7,0.4-10,0.8c-7.2,0.9-14.2,2.5-21.1,4.9c-9,3.1-17.4,7.5-25.3,12.9c-3.2,2.2-6.3,4.6-9.2,7.2
                c-2.7,2.4-5.2,4.9-7.6,7.5C41,56.7,37.1,62,33.6,67.7c-1.5,2.5-3,5.1-4.3,7.7C25.6,83,22.7,90.9,21,99.2c-0.8,3.7-1.4,7.5-1.8,11.3
                c-0.2,2.2-0.3,4.5-0.5,6.7c-0.1,1.6-0.2,3.2-0.1,4.8c0.1,3.3,0.3,6.6,0.6,9.9c0.5,5.8,1.7,11.4,3.2,17c1.1,4.2,2.6,8.3,4.3,12.4
                c2.9,6.8,6.4,13.2,10.6,19.2c1.9,2.8,4,5.5,6.2,8c1.7,2,3.5,3.9,5.3,5.7c1.7,1.8,2.6,4,2.6,6.5c-0.1,5-4.1,8.8-8.4,9.1
                c-2.9,0.2-5.4-0.7-7.5-2.8c-6-6-11.3-12.5-15.9-19.6c-3.3-5.2-6.3-10.6-8.8-16.2c-2-4.4-3.7-8.9-5.2-13.5c-1.6-5-2.9-10.1-3.7-15.3
                c-0.5-3.3-1-6.5-1.3-9.8c-0.2-2.6-0.5-5.1-0.4-7.7c0-1-0.2-2.1-0.2-3.1c0.2-2.9,0.1-5.8,0.3-8.7c0.1-2.1,0.4-4.2,0.6-6.4
                c0.3-2.5,0.7-4.9,1.1-7.4c1-5.7,2.5-11.3,4.3-16.7c1.4-4.3,3.2-8.4,5-12.5c2.8-6.2,6.3-12.1,10.1-17.8c2.7-4,5.7-7.8,9-11.4
                c2-2.2,4-4.4,6.1-6.5c2.8-2.7,5.6-5.2,8.6-7.6c3-2.5,6.2-4.8,9.4-6.9c4.9-3.2,10-6.1,15.4-8.6c4.5-2.1,9-3.9,13.7-5.5
                c4.4-1.4,8.8-2.6,13.3-3.5c3.7-0.7,7.4-1.3,11.1-1.7c3.7-0.4,7.4-0.5,11.1-0.7c2.9-0.1,5.8,0.1,8.7,0.1c2.2,0,4.4,0.3,6.6,0.5
                c3.7,0.4,7.3,1,11,1.7c2.3,0.4,4.5,1,6.8,1.6c3.7,1,7.3,2.1,10.8,3.4c4.1,1.5,8.1,3.2,12,5.2c6,2.9,11.7,6.4,17.1,10.2
                c2.9,2.1,5.7,4.4,8.5,6.7c3.5,2.9,6.6,6.2,9.8,9.4c2,2.1,3.8,4.3,5.6,6.5c2.6,3.1,4.8,6.4,7,9.7c1.6,2.5,3.1,5,4.5,7.6
                c3.3,6.1,6.1,12.4,8.4,18.9c1.7,4.8,3.1,9.7,4.1,14.7c0.7,3.5,1.3,7,1.7,10.5c0.3,2.7,0.5,5.3,0.7,8c0.2,3.7,0.2,7.4,0.1,11.1
                c-0.1,3.2-0.4,6.4-0.8,9.5c-0.6,5.1-1.5,10.2-2.8,15.3c-1.3,5.2-3,10.3-5,15.3c-1.1,2.8-2.3,5.5-3.6,8.2c-1.8,3.7-3.7,7.2-5.9,10.7
                c-2.2,3.6-4.6,7.1-7.2,10.4c-1.6,2-3.2,4-4.9,5.9c-1.7,2-3.5,3.9-5.3,5.7c-3.1,3.2-8.1,3.6-11.8,1.1c-4.7-3.2-5.2-9.7-1.7-13.6
                c0.8-0.9,1.6-1.7,2.4-2.6c3.7-3.8,7-8,10.1-12.4c3.1-4.6,5.9-9.3,8.2-14.3c3.4-7.2,5.9-14.6,7.6-22.4c0.7-3.2,1.2-6.4,1.6-9.7
                c0.2-2,0.4-3.9,0.5-5.9C224.1,125.3,224.1,123.3,224.1,121.4C224.1,121.4,224.1,121.4,224.1,121.4z')
    i2:
      card:
        type: custom:button-card
        styles: 
          card:
            - margin-top: 398px
            - border-width: 0
            - background: |
                [[[ 
                    var vent = states[variables.换气].state;   
                    var blow = states[variables.吹风].state;   
                    var heat = states[variables.取暖].state;   
                    if(vent=='on' && blow=='on' && heat=='on')    return "radial-gradient(rgb(254,111,33) -20%, rgb(0,0,0,0) 50%)" ;
                    if(vent=='on' && blow=='on' && heat=='off')   return "radial-gradient(rgb(33,150,243) -20%, rgb(0,0,0,0) 50%)" ;
                    if(vent=='on' && blow=='off' && heat=='off')  return "radial-gradient(rgb(0,188,213) -20%, rgb(0,0,0,0) 50%)" ;
                    if(vent=='off' && blow=='on' && heat=='on')   return "radial-gradient(rgb(254,111,33) -20%, rgb(0,0,0,0) 50%)" ;
                    if(vent=='off' && blow=='on' && heat=='off')  return "radial-gradient(rgb(33,150,243) -20%, rgb(0,0,0,0) 50%)" ;
                    if(vent=='off' && blow=='off' && heat=='off') return "rgb(0,0,0,0)" ;
                ]]]
            - width: 264px
            - height: 264px
    i3:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 720px
            - width: 264px
            - height: 42px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'
            - border-radius: 10px
    i4:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 830px
            - width: 264px
            - height: 42px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'
            - border-radius: 10px
    n:
      card:
        type: custom:button-card
        label: '[[[ return states[variables.浴霸].attributes.friendly_name ]]]'
        show_label: true
        styles:
          card:
            - border-width: 0
            - background: rgb(0,0,0,0)
            - margin-top: 73px
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(230,230,230)" ]]]'
            - font-size: 19px
    l1:
      card:
        type: custom:button-card
        label: |
          [[[ 
              var vent = states[variables.换气].state;   
              var blow = states[variables.吹风].state;   
              var heat = states[variables.取暖].state;   
              if(vent=='on'  && blow=='on'  && heat=='on')  return "换气+取暖";
              if(vent=='on'  && blow=='on'  && heat=='off') return "换气+吹风";
              if(vent=='on'  && blow=='off' && heat=='off') return "换气";
              if(vent=='off' && blow=='on'  && heat=='on')  return "取暖";
              if(vent=='off' && blow=='on'  && heat=='off') return "吹风";
              if(vent=='off' && blow=='off' && heat=='off') return "关闭";
          ]]]
        show_label: true
        styles:
          card:
            - border-width: 0
            - background: rgb(0,0,0,0)
            - margin-top: 314px
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(230,230,230)" ]]]'
            - font-size: 15px
    s:
      card:
        type: custom:button-card
        label: '[[[ return Math.round(states[variables.温度].state,0) ]]]'
        show_label: true
        styles:
          card:
            - border-width: 0
            - background: rgb(0,0,0,0)
            - margin-top: 405px
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(230,230,230)" ]]]'
            - font-size: 45px
    u:
      card:
        type: custom:button-card
        label: °C
        show_label: true
        styles:
          card:
            - border-width: 0
            - background: rgb(0,0,0,0)
            - margin-top: 423px
            - margin-left: -5px
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(230,230,230)" ]]]'
            - font-size: 14px
    m:
      card:
        type: custom:button-card
        icon: 'mdi:minus'
        styles:
          card:
            - margin-top: 580px
            - width: 50px
            - height: 50px
            - border-radius: 25px
            - border: '[[[ return variables.主题 =="on" ? "2px solid rgb(150,150,150)" : "2px solid rgb(180,180,180)" ]]]'
            - margin-left: '27px'
            - --mdc-ripple-color: white
            - --mdc-ripple-press-opacity: 0.3
            - background: rgb(0,0,0,0)
          icon:
            - width: 25px
            - height: 25px
            - color: '[[[ return variables.主题 =="on" ? "rgb(150,150,150)" : "rgb(180,180,180)"; ]]]'
    p:
      card:
        type: custom:button-card
        icon: 'mdi:plus'
        styles:
          card:
            - margin-top: 580px
            - width: 50px
            - height: 50px
            - border-radius: 25px
            - border: '[[[ return variables.主题 =="on" ? "2px solid rgb(150,150,150)" : "2px solid rgb(180,180,180)" ]]]'
            - margin-left: '12px'
            - --mdc-ripple-color: white
            - --mdc-ripple-press-opacity: 0.3 
            - background: rgb(0,0,0,0)
          icon:
            - width: 25px
            - height: 25px
            - color: '[[[ return variables.主题 =="on" ? "rgb(150,150,150)" : "rgb(180,180,180)"; ]]]'
    a1:
      card:
        type: custom:button-card
        label: 换气on
        show_label: true
        show_icon: true
        icon: mdi:hvac
        styles:
          card:
            - margin-top: 720px
            - margin-left: 0px
            - width: 87px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: |
                [[[ 
                    if( states[variables.换气].state=='on')   return 'rgb(0,188,213)';
                    if( states[variables.换气].state=='off')  return 'rgb(0,0,0,0)';
                ]]]
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 11px
        tap_action:
          action: call-service
          service: switch.turn_on
          target:
            entity_id: '[[[ return  variables.换气 ]]]'
    a2:
      card:
        type: custom:button-card
        label: 吹风on
        show_label: true
        show_icon: true
        icon: mdi:blur
        styles:
          card:
            - margin-top: 720px
            - margin-left: 1px
            - width: 87px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: |
                [[[ 
                    if( states[variables.吹风].state=='on')   return 'rgb(33,150,243)';
                    if( states[variables.吹风].state=='off')  return 'rgb(0,0,0,0)';
                ]]]
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 11px
        tap_action:
          action: call-service
          service: switch.turn_on
          target:
            entity_id: '[[[ return  variables.吹风 ]]]'
    a3:
      card:
        type: custom:button-card
        label: 取暖on
        show_label: true
        show_icon: true
        icon: mdi:weather-sunny
        styles:
          card:
            - margin-top: 720px
            - margin-left: 2px
            - width: 87px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: |
                [[[
                    if( states[variables.取暖].state=='on')   return 'rgb(254,111,33)';
                    if( states[variables.取暖].state=='off')  return 'rgb(0,0,0,0)';
                ]]]
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 11px
        tap_action:
          action: call-service
          service: switch.turn_on
          target:
            entity_id: '[[[ return  variables.取暖 ]]]'
    a4:
      card:
        type: custom:button-card
        label: 换气off
        show_label: true
        show_icon: true
        icon: mdi:hvac-off
        styles:
          card:
            - margin-top: 830px
            - margin-left: 0px
            - width: 88px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: |
                [[[ 
                    if( states[variables.换气].state=='on')   return 'rgb(0,0,0,0)';
                    if( states[variables.换气].state=='off')  return variables.主题 =="on" ? "rgb(180,180,180)" : "rgb(150,150,150)";
                ]]]
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 11px
        tap_action:
          action: call-service
          service: switch.turn_off
          target:
            entity_id: '[[[ return  variables.换气 ]]]'
    a5:
      card:
        type: custom:button-card
        label: 吹风off
        show_label: true
        show_icon: true
        icon: mdi:blur-off
        styles:
          card:
            - margin-top: 830px
            - margin-left: 1px
            - width: 87px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: |
                [[[ 
                    if( states[variables.吹风].state=='on')   return 'rgb(0,0,0,0)';
                    if( states[variables.吹风].state=='off')  return variables.主题 =="on" ? "rgb(180,180,180)" : "rgb(150,150,150)";
                ]]]
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 11px
        tap_action:
          action: call-service
          service: switch.turn_off
          target:
            entity_id: '[[[ return  variables.吹风 ]]]'
    a6:
      card:
        type: custom:button-card
        label: 取暖off
        show_label: true
        show_icon: true
        icon: mdi:weather-sunny-off
        styles:
          card:
            - margin-top: 830px
            - margin-left: 2px
            - width: 87px
            - height: 42px 
            - border-radius: 10px
            - border-width: 0
            - background: |
                [[[
                    if( states[variables.取暖].state=='on')   return 'rgb(0,0,0,0)';
                    if( states[variables.取暖].state=='off')  return variables.主题 =="on" ? "rgb(180,180,180)" : "rgb(150,150,150)";
                ]]]
          icon:
            - width: 20px
            - height: 20px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
          label: 
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 11px
        tap_action:
          action: call-service
          service: switch.turn_off
          target:
            entity_id: '[[[ return  variables.取暖 ]]]'
 
