电脑屏幕:
  entity_picture: '[[[ return states[variables.屏幕]?.attributes?.entity_picture ]]]'
  show_entity_picture: true
  show_label: true 
  label: |
    [[[
        return states[variables.电脑].state=="off" ? "关机" :"";
    ]]] 
  styles:
    label:
      - font-size: 30px
      - color: '[[[ return variables.主题=="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
    entity_picture:
      - width: 98%
      - height: 98%
      - border-radius: 10px
    card: 
      - padding: 0
      - width: 400px 
      - height: 260px
      - border-radius: 10px
      - border-width: 0
      - background: '[[[ return variables.主题=="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
电脑硬盘: 
  styles: 
    grid:
      - grid-template-areas: |
          "图标 名称"
          "图标 进度条"
          "图标 文本"
      - grid-template-columns: 25% 75%
      - grid-template-rows: 33% 33% 33%
      - text-align: left
      - font-size: 13px
      - color: '[[[ return variables.主题=="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
    card:
      - padding: 1% 0 1% 0
      - width: 400px
      - height: 59px
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题=="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
  custom_fields:
    图标:
      card:
        type: custom:button-card
        icon: mdi:harddisk
        show_icon: true
        styles:
          icon:
            - color: '[[[ return variables.主题=="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
    名称: '[[[ return variables.名称 ]]]'
    文本: '[[[ return states[variables.硬盘空闲].state + " GB 可用,&ensp;共 "+ states[variables.硬盘总共].state +" GB"]]]'
    进度条:
      card:
        type: custom:button-card
        icon: mdi:harddisk
        show_icon: true
        show_label: true
        label: " "
        styles:
          label:
            - padding: 0
            - width: 200px
            - height: 15px
            - border-width: 0
            - border-radius: 0px
            - background: | 
                [[[
                    var per = states[variables.硬盘百分比].state;
                    return `linear-gradient(to right, #00aadd ${per}%, transparent ${per}%)`;
                ]]]
          card:
            - padding: 0
            - width: 200px
            - height: 15px
            - border-width: 0
            - border-radius: 0px
            - background: '[[[ return variables.主题=="on" ? "rgb(180,180,180)" : "rgb(150,150,150)" ]]]'
电脑图表网络: 
  styles:
    grid:
      - grid-template-areas: | 
          "图表"
      - grid-template-columns: 100%
      - grid-template-rows: 100%
    card:  
      - padding: 0
      - width: 400px
      - height: 260px
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题=="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
  custom_fields:
    图表:
      card:
        type: custom:apexcharts-card
        card_mod:  
          style: '[[[ return theme_apexcharts()]]]'
        header:
          show: true
          show_states: true
          colorize_states: true
          standard_format: true
        graph_span: 15m    
        apex_config:
          grid:
            position: front
            row:
              colors:
                - black
                - transparent
              opacity: 0.1
            xaxis:
              lines:
                show: false
            yaxis:
              lines:
                show: false
          chart:
            height: 200 
        now:
          show: true
          color: "#80a4ff"
          label: 现在
        series:   
          - entity: '[[[ return variables.项目1 ]]]'
            name: '[[[ return variables.项目1名称 ]]]'
            transform: "return x / 1024;"
            color: "#00aadd"
            unit: "KB" 
            fill_raw: last
            stroke_width: 1  
          - entity: '[[[ return variables.项目2 ]]]'
            name: '[[[ return variables.项目2名称 ]]]'
            transform: "return x / 1024;"
            color: "#ff5500"
            unit: "KB" 
            fill_raw: last
            stroke_width: 1  
电脑图表cpu内存: 
  styles: 
    grid:
      - grid-template-areas: |
          "图表"
      - grid-template-columns: 100%
      - grid-template-rows: 100%
    card:  
      - padding: 0
      - width: 400px
      - height: 260px
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题=="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
  custom_fields:
    图表:
      card:
        type: custom:apexcharts-card
        card_mod:  
          style: '[[[ return theme_apexcharts()]]]'
        header:
          show: true
          show_states: true
          colorize_states: true
          standard_format: true
        graph_span: 15m 
        yaxis:
          - min: 0 
            max: 100
        apex_config:
          grid:
            position: front
            row:
              colors:
                - black
                - transparent
              opacity: 0.1
            xaxis:
              lines:
                show: false
            yaxis:
              lines:
                show: false
          chart:
            height: 200 
        now:
          show: true
          color: "#80a4ff"
          label: 现在
        series:   
          - entity: '[[[ return variables.项目1 ]]]'
            name: '[[[ return variables.项目1名称 ]]]'
            color: "#00aadd"
            unit: "%" 
            type: area
            fill_raw: last
            stroke_width: 1   
          - entity: '[[[ return variables.项目2 ]]]'
            name: '[[[ return variables.项目2名称 ]]]'  
            color: "#ff5500"
            unit: "%" 
            type: area
            fill_raw: last
            stroke_width: 1   
