门铃:
  entity_picture: '[[[ return states[variables.门铃]?.attributes?.entity_picture ]]]'
  show_entity_picture: true
  show_label: true 
  label: |
    [[[
        return states[variables.门铃].state=="off" ? "关机" :"";
    ]]] 
  styles:
    label:
      - font-size: 30px
      - color: '[[[ return variables.主题=="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
    entity_picture:
      - width: 100%
      - height: 100%
      - border-radius: 10px
    card: 
      - padding: 0
      - width: 400px 
      - height: 260px 
      - border-radius: 10px
      - border-width: 0
      - background: '[[[ return variables.主题=="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'