action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_none(420); ]]]'  ## 单卡宽度310,侧边栏宽度80,[80+310=390]
    content: 
      type: vertical-stack
      cards:
        - type: custom:button-card
          template: 冰箱图表
          variables:              
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
            设定温度: sensor.refrigerator_setting_temp_right
            实际温度: sensor.refrigerator_temp_right
            设定温度名称: 冷藏室设定温度
            实际温度名称: 冷藏室温度
        - type: custom:button-card
          template: 冰箱图表 
          variables:              
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
            设定温度: sensor.refrigerator_setting_temp_left
            实际温度: sensor.refrigerator_temp_left
            设定温度名称: 冷冻室设定温度
            实际温度名称: 冷冻室温度
        - type: custom:button-card
          template: 冰箱
          variables:              
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
            冷藏门状态: binary_sensor.refrigerator_door_right
            冷冻门状态: binary_sensor.refrigerator_door_left