action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_none(470); ]]]'  ## 单卡宽度310,侧边栏宽度80,[80+310=390]
    content: 
      type: horizontal-stack
      cards:
        - type: custom:button-card
          template: 扫地机器人 
          variables:              
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
            扫地机器人: vacuum.saodijiqiren 
            充电状态: sensor.dreame_cn_1023400391_p2140_charging_state_p_3_2 ##【正在充电, 不在充电, 正在回充】
            回充: button.dreame_cn_1023400391_p2140_start_charge_a_3
            定位: button.dreame_cn_1023400391_p2140_position_a_7_1
            清扫模式: select.dreame_cn_1023400391_p2140_mode_p_2_3        ## 【安静静音 标准 强力 全速模式（Max）】
            出水量: number.dreame_cn_1023400391_p2140_mop_mode_p_4_5      ## 出水量【1 2 3】
            语音音量: number.dreame_cn_1023400391_p2140_volume_p_7_1
            地毯增压: select.dreame_cn_1023400391_p2140_carpet_press_p_4_12        ##【关闭 打开】
            断点续扫: select.dreame_cn_1023400391_p2140_break_point_restart_p_4_11 ##【关闭 打开】
            滤芯剩余百分比: sensor.haocai_saodijiqiren_lvxin
            滤芯剩余时间: sensor.saodijiqiren_lvwang_shengyushijian
            滤芯重置: button.dreame_cn_1023400391_p2140_reset_filter_life_a_11_1
            主刷剩余百分比: sensor.haocai_saodijiqiren_zhushua
            主刷剩余时间: sensor.saodijiqiren_zhushua_shengyushijian
            主刷重置: button.dreame_cn_1023400391_p2140_reset_brush_life_a_9_1
            边刷剩余百分比: sensor.haocai_saodijiqiren_bianshua
            边刷剩余时间: sensor.saodijiqiren_bianshua_shengyushijian
            边刷重置: button.dreame_cn_1023400391_p2140_reset_brush_life_a_10_1