action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style: '[[[ return theme_none(410)]]]'
    content:
      type: horizontal-stack
      cards:
        - type: vertical-stack
          cards:
            - type: custom:button-card
              template: 门铃
              variables:      
                主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
                门铃: camera.door