action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_none(1000); ]]]'  ## 单卡宽度250
    content: 
      type: vertical-stack               
      cards:     
        - type: horizontal-stack               
          cards:            
            - type: custom:button-card 
              template: 空气炸锅
              variables:
                主题: '[[[ return theme() ]]]'
                空气炸锅: sensor.chufang_kongqizhaguo ## [关机, 待机, 暂停, 预约中, 烹饪中, 预热中, 烹饪完成, 预热完成, 预热暂停, 抽锅暂停]
                开始亨饪: text.careli_cn_426704626_maf03_start_cook_a_3_1 ## [M0,手动,15,180,0,0,0] [M1,薯条,15,200,0,0,0]
                停止亨饪: button.careli_cn_426704626_maf03_cancel_cooking_a_2_2
                暂停亨饪: button.careli_cn_426704626_maf03_pause_a_2_3
                继续亨饪: button.careli_cn_426704626_maf03_resume_cook_a_3_2
                工作时间: number.careli_cn_426704626_maf03_target_time_p_2_3
                工作温度: number.careli_cn_426704626_maf03_target_temperature_p_2_4
                剩余时间: sensor.careli_cn_426704626_maf03_left_time_p_2_5
            - type: custom:button-card      
              template: 电饭煲  
              variables:  
                主题: '[[[ return theme() ]]]'
                电饭煲: sensor.chufang_dianfanbao ## [待机中, 烹饪中, 保温中, 预约中]
                开始亨饪: text.chunmi_cn_119441120_normal3_start_cook_a_2_1 ## [烹饪模式(int)][1:精煮饭、2:快煮饭、3:煮粥、4:保温]
                停止亨饪: button.chunmi_cn_119441120_normal3_cancel_cooking_a_2_2
            - type: custom:button-card
              template: 电压力锅       
              variables:  
                主题: '[[[ return theme() ]]]'
                电压力锅: sensor.chufang_dianyaliguo  ## [待机中, 工作中, 保温中, 预约中, 故障]  
                开始亨饪: text.chunmi_cn_824782007_mini1_start_cook_a_2_1  ## [烹饪模式(int)][1:米饭、3:牛羊肉、4:鸡鸭肉、7:煲汤、9:开盖煮、10:保温]
                停止亨饪: button.chunmi_cn_824782007_mini1_cancel_cooking_a_2_2
                剩余时间: sensor.chunmi_cn_824782007_mini1_left_time_p_2_5  
            - type: custom:button-card
              template: 蒸煮锅    
              variables:  
                主题: '[[[ return theme() ]]]'
                蒸煮锅: sensor.chufang_zhengzhuguo  ## [休眠中, 待机中, 烹饪中, 暂停中, 预约中, 烹饪完成, 故障中, 烹饪完成升温中, 烹饪完成降温中]
                模式: select.deerma_cn_647227974_v3_mode_p_2_2  ## 模式选择（火锅，蒸煮，煲汤，煮粥，煮面，保温）
                开始亨饪: button.deerma_cn_647227974_v3_start_cook_a_2_1 
                停止亨饪: button.deerma_cn_647227974_v3_cancel_cooking_a_2_2
                暂停亨饪: button.deerma_cn_647227974_v3_pause_a_2_3   
                继续亨饪: button.deerma_cn_647227974_v3_continue_cook_a_4_6 
                目标时间: number.deerma_cn_647227974_v3_target_time_p_2_9
                火力等级: number.deerma_cn_647227974_v3_heat_level_p_2_6
                剩余时间: sensor.deerma_cn_647227974_v3_left_time_p_2_3

        - type: horizontal-stack              
          cards:                   
            - type: custom:button-card    
              template: 破壁机 
              variables:  
                主题: '[[[ return theme() ]]]'
                破壁机: sensor.chufang_pobiji  ## [Idle, Busy, Paused, Delay, Sleep, Keep Warm, Completed, Fault]
                开始亨饪: text.chunmi_cn_682421582_a1_start_cook_a_2_1  ##  [烹饪模式(int)][1豆浆、2果蔬汁、3浓汤、4奶昔、5玉米汁、6保温]
                停止亨饪: button.chunmi_cn_682421582_a1_cancel_cooking_a_2_2  #停止亨饪
                剩余时间: sensor.chunmi_cn_682421582_a1_left_time_p_2_3       #剩余时间
            - type: custom:button-card   
              template: 洗碗机
              variables:
                主题: '[[[ return theme() ]]]'
                洗碗机: sensor.chufang_xiwanji ## [Power Off, Power On]
                电源: switch.180319907614846_power
                保管: switch.180319907614846_storage
                童锁: lock.180319907614846_child_lock 
                剩余时间: sensor.180319907614846_time_remaining
                程序: sensor.180319907614846_progress 
                门状态: binary_sensor.180319907614846_door
                漂洗计状态: binary_sensor.haocai_xiwanji_piaoxiji
                洗碗盐状态: binary_sensor.haocai_xiwanji_xiwanyan             
            - type: custom:button-card
              template: 油烟机
              variables:  
                主题: '[[[ return theme() ]]]'
                停止: switch.youyanji      #关闭开关       
                功率: sensor.youyanji   #功率
            - type: custom:button-card
              template: 净水器 
              variables:  
                主题: '[[[ return theme() ]]]'
                出水水质: sensor.yunmi_cn_103342738_lx5_tds_out_p_3_2       #出水水质
                入水水质: sensor.yunmi_cn_103342738_lx5_tds_in_p_3_1         #入水水质
                温度: sensor.yunmi_cn_103342738_lx5_temperature_p_2_1     #温度
                三合一滤芯: sensor.haocai_jingshuiqi_3in1 #3合一滤芯
                RO滤芯: sensor.haocai_jingshuiqi_ro   #RO滤芯