action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_none(780); ]]]'  ## 单卡宽度310,侧边栏宽度80,[80+310+310+80=780]
    content: 
      type: horizontal-stack
      cards:
        - type: custom:button-card  
          template: 水暖毯
          variables: 
            主题: '[[[ return theme() ]]]'
            水暖毯: climate.shuinuantan 
            附加信息: 左侧  ## 附加信息位置 [左侧] [右侧] [无] [无：可删除下方引用]
            防冻: switch.shuinuantan_antifreeze
            防烫伤: switch.shuinuantan_antiscald
            睡眠: switch.shuinuantan_sleep
            指示灯: light.shuinuantan_light_keting
            提示音: switch.shuinuantan_alarm_keting
            按键锁: switch.shuinuantan_locked_keting
            水位提示: sensor.shuinuantan_water_keting
        - type: custom:button-card  
          template: 地暖
          variables: 
            主题: '[[[ return theme() ]]]'
            地暖: climate.dinuan
            附加信息: 右侧  ## 附加信息位置 [左侧] [右侧] [无]