action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style: '[[[ return theme_none(540) ]]]'
    content:
      type: vertical-stack
      cards:
        - type: custom:button-card    
          template: 主题信息卡片
          variables:
            主题: 
              模式开关: '[[[ return variables.主题?.模式开关]]]'
              模式: '[[[ return variables.主题?.模式]]]'
              色相开关: '[[[ return variables.主题?.色相开关]]]'
              色相: '[[[ return variables.主题?.色相]]]'

  