待办事项:
  triggers_update: 
    - '[[[ return variables.待办清单实体 ]]]'
    - '[[[ return variables.待办清单NR实体 ]]]'
    - '[[[ return variables.待办清单名称 ]]]'
    - '[[[ return variables.待办清单描述 ]]]'
    - '[[[ return variables.待办清单时间 ]]]'
  styles:
    card:       
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - padding: 0
      - background: rgb(0,0,0,0)
    grid:                              
      - grid-template-areas: |   
          "item1" "item2" "item3" "item4" "item5" 
          "item6" "item7" "item8" "item9" "item10"  
          "item" 
      - grid-template-columns: 100%
      - grid-auto-rows: minmax(auto, auto)
      - grid-auto-flow: row
  custom_fields:
    item: 
      card:
        type: custom:button-card 
        styles:
          grid:
            - grid-template-areas: |         
                ". ."     
                "日期 新增"
                "名称 名称"
                "描述 描述"     
                ". ."     
            - grid-template-columns: 7fr 1fr
            - grid-template-rows: 1vw 1fr 1fr 1fr 1vw
          card:
            - cursor: none
            - width: 93vw  
            - height: 25vw
            - --mdc-ripple-press-opacity: 0  
            - padding: 0 0 0 3vw 
            - border-radius: 3vw
            - border-width: 0
            - background: '[[[ return variables.主题 == "on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
        custom_fields:
          新增:
            card:
              type: custom:button-card  
              show_label: true
              label: 新增
              styles:
                label:
                  - font-size: 3.5vw
                  - font-weight: bold
                  - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
                card:
                  - cursor: none
                  - --mdc-ripple-press-opacity: 0.5
                  - padding: 0
                  - width: 12vw
                  - height: 6vw
                  - border-radius: 3vw
                  - right: 2vw
                  - top: -1vw
                  - justify-self: right
                  - background: rgb(0,250,0,0.5)
              tap_action:
                action: call-service
                service: todo.add_item
                data: 
                  item: '[[[ return states[variables.待办清单名称]?.state || "待办项目"]]]'
                  due_date: |
                    [[[ 
                        let text_date = states[variables.待办清单时间]?.state;
                        if (!text_date) {
                            const today = new Date();
                            const year = today.getFullYear();
                            const month = String(today.getMonth() + 1).padStart(2, '0');
                            const day = String(today.getDate()).padStart(2, '0');
                            text_date = `${year}-${month}-${day}`;
                        } 
                        else {
                            // 检查并匹配 2025/05/17、2025.05.17、20250517、2025-05-17 这几种格式
                            const match = text_date.match(
                                /^(\d{4})([\/\-\.]?)(\d{2})\2(\d{2})$|^(\d{4})(\d{2})(\d{2})$/
                            );
                            if (match) {
                                if (match[1]) {
                                    text_date = `${match[1]}-${match[3]}-${match[4]}`;
                                } 
                                else if (match[5]) {
                                    text_date = `${match[5]}-${match[6]}-${match[7]}`;
                                }
                            } 
                            else {
                                text_date = '';
                            }
                        }
                        return text_date;
                    ]]]
                  description: '[[[ return states[variables.待办清单描述]?.state ?? ""]]]'
                target:
                  entity_id: '[[[ return variables.待办清单实体 ]]]'
          日期: 
            card:
              type: custom:button-card 
              styles:     
                grid:                              
                  - grid-template-areas: |
                      "日期1"
                  - grid-template-columns: 100%
                  - grid-template-rows: 100%
                card:
                  - height: 6vw
                  - width: 70vw
                  - border-radius: 1.5vw
                  - background: rgb(0,0,0,0)
                  - border: '[[[ return variables.主题 == "on" ? "1px solid rgb(0,0,0,0.8)" : "1px solid rgb(255,255,255,0.8)"; ]]]'
              custom_fields:
                日期1: 
                  card:
                    type: custom:xiaoshi-text-card
                    icon: mdi:calendar-edit
                    entity: '[[[ return variables.待办清单时间 ]]]'
                    height: 6vw
                    width: 70vw
                    border-radius: 1.5vw
                    theme: '[[[ return variables.主题 ]]]'
          名称: 
            card:
              type: custom:button-card 
              styles:     
                grid:                              
                  - grid-template-areas: |
                      "名称1"
                  - grid-template-columns: 100%
                  - grid-template-rows: 100%
                card:
                  - height: 6vw
                  - width: 70vw
                  - border-radius: 1.5vw
                  - background: rgb(0,0,0,0)
                  - border: '[[[ return variables.主题 == "on" ? "1px solid rgb(0,0,0,0.8)" : "1px solid rgb(255,255,255,0.8)"; ]]]'
              custom_fields:
                名称1: 
                  card:
                    type: custom:xiaoshi-text-card
                    icon: mdi:calendar-edit
                    entity: '[[[ return variables.待办清单名称 ]]]'
                    height: 6vw
                    width: 70vw
                    border-radius: 1.5vw
                    theme: '[[[ return variables.主题 ]]]'
          描述: 
            card:
              type: custom:button-card 
              styles:     
                grid:                              
                  - grid-template-areas: |
                      "描述1"
                  - grid-template-columns: 100%
                  - grid-template-rows: 100%
                card:
                  - height: 6vw
                  - width: 70vw
                  - border-radius: 1.5vw
                  - background: rgb(0,0,0,0)
                  - border: '[[[ return variables.主题 == "on" ? "1px solid rgb(0,0,0,0.8)" : "1px solid rgb(255,255,255,0.8)"; ]]]'
              custom_fields:
                描述1: 
                  card:
                    type: custom:xiaoshi-text-card
                    icon: mdi:calendar-edit
                    entity: '[[[ return variables.待办清单描述 ]]]'
                    height: 6vw
                    width: 70vw
                    border-radius: 1.5vw
                    theme: '[[[ return variables.主题 ]]]'
    item1: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 0
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item2: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 1
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item3: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 2
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item4: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 3
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item5: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 4
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item6: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 5
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item7: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 6
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item8: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 7
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item9: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 8
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'
    item10: 
      card:
        type: custom:button-card 
        template: 待办事项显示明细
        variables:
          num: 9
          待办清单实体: '[[[return variables.待办清单实体]]]'
          待办清单NR实体: '[[[return variables.待办清单NR实体]]]'
          待办清单名称: '[[[return variables.待办清单名称]]]'
          待办清单描述: '[[[return variables.待办清单描述]]]'
          待办清单时间: '[[[return variables.待办清单时间]]]'
          主题: '[[[return variables.主题]]]'

待办事项显示明细:
  triggers_update: 
    - '[[[ return variables.待办清单实体 ]]]'
    - '[[[ return variables.待办清单NR实体 ]]]'
    - '[[[ return variables.待办清单名称 ]]]'
    - '[[[ return variables.待办清单描述 ]]]'
    - '[[[ return variables.待办清单时间 ]]]'
  show_label: true
  label: |
    [[[
        var items = states[variables.待办清单NR实体]?.attributes?.items || [];
        if (items.length == 0) {
          return "无待办事项"
        }
        if (items.length > variables.num) {
            var due = items[variables.num]?.due || "";
            var summary = items[variables.num]?.summary || "";
            var description = items[variables.num]?.description || "";
            return  `待办日期:&ensp;${due}<br>待办名称:&ensp;${summary}<br>待办描述:&ensp;${description}`
        }
    ]]]
  custom_fields:
    background:
      card:
        type: custom:button-card  
        styles:
          card:
            - padding: 0
            - width: 93vw  
            - height: 19vw
            - border-radius: 3vw
            - background: '[[[ return variables.主题 == "on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
            - display: |
                [[[
                    var items = states[variables.待办清单NR实体]?.attributes?.items || [];
                    return variables.num=="0" ? "" : items.length < variables.num+1 ? "none" : "";
                ]]]
    delete:
      card:
        type: custom:button-card  
        show_label: true
        label: 删除
        styles:
          label:
            - font-size: 3.5vw
            - font-weight: bold
            - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
          card:
            - cursor: none
            - --mdc-ripple-press-opacity: 0.5
            - padding: 0
            - width: 12vw
            - height: 6vw
            - border-radius: 3vw
            - background: rgb(255,0,0,0.5)
            - display: |
                [[[
                    var items = states[variables.待办清单NR实体]?.attributes?.items || [];
                    return items.length < variables.num+1 ? "none" : "";
                ]]]
        tap_action:
          action: call-service
          service: todo.remove_item
          data: 
            item: |
              [[[
                  var items = states[variables.待办清单NR实体]?.attributes?.items || [];
                  if (items.length >= variables.num) {
                    return items.length > variables.num ? items[variables.num]?.summary : "";
                  }
              ]]]
          target:
            entity_id:
              - '[[[ return variables.待办清单实体]]]'
  styles:
    custom_fields:
      background:
        - padding: 0
        - width: 93vw  
        - height: 19vw
        - position: absolute 
        - align-self: start
        - justify-self: end
      delete:
        - padding: 0
        - width: 12vw
        - height: 6vw
        - position: absolute 
        - right: 2vw
        - top: 1.5vw
        - align-self: start
        - justify-self: end
        - z-index: 1
    label:
      - width: 85vw  
      - font-size: 3.5vw
      - text-align: left
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
      - z-index: 1
    card:
      - cursor: none
      - width: 93vw  
      - height: 20vw
      - --mdc-ripple-press-opacity: 0.3
      - padding: 0 0 0 0 
      - border-radius: 3vw
      - border-width: 0
      - backgropund: rgb(0,0,0,0)
      - display: |
          [[[ 
              var items = states[variables.待办清单NR实体]?.attributes?.items || [];
              return variables.num=="0" ? "" : items.length < variables.num+1 ? "none" : "";
          ]]]
  