空气质量AQI:
  graph_span: 1d
  header:
    show: true
    show_states: true
  cache: true
  yaxis:
    - min: ~1000
      max: ~-100
      apex_config:
        tickAmount: 5
  all_series_config:
    fill_raw: last
    stroke_width: 1
    curve: smooth
    float_precision: 0
    show:
      legend_value: false
    group_by:
      func: avg
      duration: 60min
    header_actions:
      tap_action:
        action: none
      hold_action:
        action: none
  apex_config:
    chart:
      height: 160px  