主界面_燃气:  
  triggers_update: 
    - sensor.xian_gas
  styles:
    grid:
      - grid-template-areas: >
          "余额 预计"  
      - grid-template-columns: 60% 40%  
      - grid-template-rows: 100%
      - text-align: left  
      - width: 240px  
      - font-size: 14px 
      - font-weight: bold
      - color: '[[[ return entity.state < 21 ? "rgb(250,50,0)" : "rgb(255,255,255)"]]]'
    card: 
      - padding: 0
      - background: rgb(0,0,0,0)
      - width: 240px
  custom_fields:
    余额: '[[[ return "燃气余额:&ensp;"+entity?.state+"元";  ]]]'
    预计: '[[[ return "预计:&ensp;"+entity?.attributes?.剩余天数+"天";  ]]]'
  tap_action:   
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        style: '[[[ return theme_none(410)]]]'
        content:                
          type: vertical-stack
          cards:                 
            - type: custom:button-card  
              template: 燃气信息卡片     
              variables:     
                燃气: sensor.xian_gas
                主题: '[[[ return theme() ]]]'
            - type: custom:apexcharts-card
              card_mod: 
                style: '[[[ return theme_apexcharts() ]]]'
              config_templates: 每月燃气曲线
              series:   
                - entity: sensor.xian_gas

