HA更新信息卡片:         
  triggers_update: all
  styles:
    grid:   
      - grid-template-areas: >
          "update1"
          "update2"
      - grid-template-columns: 100%
      - grid-template-rows: 50px
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题 == "on" ? "rgb(255,255,255)" : "rgb(50,50,50)"; ]]]' 
      - font-size: 15px
      - font-weight: bold
      - text-align: left
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]' 
  custom_fields:
    update1:
      card:
        type: markdown
        content: |-
          {%set num =states.update|selectattr('state','eq','on')|list|count%}
          {% if num >0 %}
          HA更新设备: <font color=red >{{num}}</font>
          {% else %}
          HA更新设备: 0
          {% endif %}
        card_mod: 
          style: '[[[ return theme_markdown() ]]]'
    update2:
      card:
        type: custom:battery-state-card
        icon: mdi:update
        card_mod: 
          style: '[[[ return theme_battery() ]]]'
        filter:
          include:
            - name: entity_id
              value: update.*
          exclude:
            - name: state
              value: 'Off'

  