HA版本信息卡片:         
  triggers_update: all
  styles:
    grid:   
      - grid-template-areas: >
          "名称 名称 名称"
          "core core1 core2"
          "supervisor supervisor1 supervisor2"
          "os os1 os2"
          "node_red node_red1 node_red2"
      - grid-template-columns: 30% 35% 35%
      - grid-template-rows: 50px 40px 40px 40px 40px
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题 == "on" ? "rgb(255,255,255)" : "rgb(50,50,50)"; ]]]' 
      - height: 210px
      - font-size: 15px
      - font-weight: bold
      - text-align: left
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]' 
  custom_fields:
    名称:
      card: 
        type: custom:button-card 
        label: HA版本信息
        show_label: true
        styles:
          card:
            - padding: 0
            - border-width: 0
            - cursor: none
            - --mdc-ripple-press-opacity: 0
            - border-radius: 10px
            - height: 50px
            - background: rgb(0,0,0,0)
          label:
            - font-size: 20px
            - font-weight: bold
            - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]' 
    core: Core
    supervisor: Supervisor
    node_red: Node Red
    os: Operating System
    core1:
      card: 
        type: custom:button-card 
        template: HA版本信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.ha_core ]]]'
    core2:
      card: 
        type: custom:button-card 
        template: HA版本信息样式模板2
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.ha_core ]]]'
    supervisor1:
      card: 
        type: custom:button-card 
        template: HA版本信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.ha_supervisor ]]]' 
    supervisor2:
      card: 
        type: custom:button-card 
        template: HA版本信息样式模板2
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.ha_supervisor ]]]' 
    os1:
      card: 
        type: custom:button-card 
        template: HA版本信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.operating_system ]]]' 
    os2:
      card: 
        type: custom:button-card 
        template: HA版本信息样式模板2
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.operating_system ]]]' 
    node_red1:
      card: 
        type: custom:button-card 
        template: HA版本信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.node_red ]]]' 
    node_red2:
      card: 
        type: custom:button-card 
        template: HA版本信息样式模板2
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.node_red ]]]' 

HA版本信息样式模板1:
  layout: name_state
  show_icon: false
  show_label: true
  show_state: true
  name: |
    [[[
        if(states[variables.entity]?.state) return "当前版本";
        return "" 
    ]]]
  state_display: |
    [[[
        return states[variables.entity]?.attributes?.installed_version ?? "";
    ]]]
  styles: 
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 0
      - background: rgb(0,0,0,0)
      - height: 40px
    name: 
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: |
          [[[
              var installed_version=states[variables.entity]?.attributes?.installed_version;
              var latest_version=states[variables.entity]?.attributes?.latest_version;
              if (installed_version!=latest_version) return "rgb(255,20,0)";
              else return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)";
          ]]]
    state:
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: |
          [[[
              var installed_version=states[variables.entity]?.attributes?.installed_version;
              var latest_version=states[variables.entity]?.attributes?.latest_version;
              if (installed_version!=latest_version) return "rgb(255,20,0)";
              else return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)";
          ]]]
HA版本信息样式模板2:
  layout: name_state
  show_icon: false
  show_label: true
  show_state: true
  name: |
    [[[
        if(states[variables.entity]?.state) return "最新版本";
        return "" 
    ]]]
  state_display: |
    [[[
        return states[variables.entity]?.attributes?.latest_version ?? "";
    ]]]
  styles: 
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 0
      - background: rgb(0,0,0,0)
      - height: 40px
    name: 
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
    state:
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'