HA离线信息卡片:         
  triggers_update: all
  styles:
    grid:   
      - grid-template-areas: >
          "outline1"
          "outline2"
      - grid-template-columns: 100%
      - grid-template-rows: 50px
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题 == "on" ? "rgb(255,255,255)" : "rgb(50,50,50)"; ]]]' 
      - font-size: 15px
      - font-weight: bold
      - text-align: left
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]' 
  custom_fields:
    outline1:
      card:
        type: markdown
        content: |-
          {%set num =states
                      |rejectattr('entity_id','search','xiaomi_cn_mitv')
                      |rejectattr('entity_id','search','dmaker_cn_921911289')
                      |rejectattr('entity_id','search','xunhuanshan')
                      |rejectattr('entity_id','search','pc_')
                      |rejectattr('entity_id','search','xiaomidianshi')
                      |rejectattr('entity_id','search','sou_suo')
                      |map(attribute='state')
                      |select('in',['unavailable'])
                      |list |count %}
          {% if num >0 %}
          HA离线设备: <font color=red >{{num}}</font>
          {% else %}
          HA离线设备: 0
          {% endif %}
        card_mod: 
          style: '[[[ return theme_markdown() ]]]'
    outline2:
      card:
        type: custom:battery-state-card
        icon: mdi:power-plug-off
        card_mod: 
          style: '[[[ return theme_battery() ]]]'
        filter:
          include:
            - name: state
              value: unavailable
          exclude:
            - name: entity_id
              value: button.xiaomi_cn_mitv*
            - name: entity_id
              value: select.xiaomi_cn_mitv*
            - name: entity_id
              value: switch.xiaomi_cn_mitv*
            - name: entity_id
              value: number.xiaomi_cn_mitv*
            - name: entity_id
              value: notify.xiaomi_cn_mitv*
            - name: entity_id
              value: sensor.xiaomi_cn_mitv*
            - name: entity_id
              value: text.xiaomi_cn_mitv*
            - name: entity_id
              value: media_player.xiaomi_cn_mitv*
            - name: entity_id
              value: button.dmaker_cn_921911289*
            - name: entity_id
              value: select.dmaker_cn_921911289*
            - name: entity_id
              value: switch.dmaker_cn_921911289*
            - name: entity_id
              value: number.dmaker_cn_921911289*
            - name: entity_id
              value: light.dmaker_cn_921911289*
            - name: entity_id
              value: fan.xunhuanshan*
            - name: entity_id
              value: sensor.dmaker_cn_921911289*
            - name: entity_id
              value: text.dmaker_cn_921911289*
            - name: entity_id
              value: select.xiaomidianshi*
            - name: entity_id
              value: sensor.pc_*
            - name: entity_id
              value: camera.pc_screen
            - name: entity_id
              value: weather.sou_suo_cheng_shi

  