HA资源信息卡片:         
  triggers_update: all
  styles:
    grid:   
      - grid-template-areas: >
          "名称 名称 名称"
          "core core1 core2"
          "supervisor supervisor1 supervisor2"
          "node_red node_red1 node_red2"
          "desk desk1 desk2"
      - grid-template-columns: 20% 40% 40%
      - grid-template-rows: 50px 40px 40px 40px 40px
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 10px
      - background: '[[[ return variables.主题 == "on" ? "rgb(255,255,255)" : "rgb(50,50,50)"; ]]]' 
      - height: 210px
      - font-size: 15px
      - font-weight: bold
      - text-align: left
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]' 
  custom_fields:
    名称:
      card: 
        type: custom:button-card 
        label: HA资源信息
        show_label: true
        styles:
          card: 
            - padding: 0
            - border-width: 0
            - cursor: none
            - --mdc-ripple-press-opacity: 0
            - border-radius: 10px
            - height: 50px
            - background: rgb(0,0,0,0)
          label:
            - font-size: 20px
            - font-weight: bold
            - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]' 
    core: Core
    supervisor: Supervisor
    node_red: Node Red
    desk: Desk硬盘
    core1:
      card: 
        type: custom:button-card 
        template: HA资源信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          name: CPU
          entity: '[[[ return variables.ha_core_cpu ]]]' 
    core2:
      card: 
        type: custom:button-card 
        template: HA资源信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          name: 内存
          entity: '[[[ return variables.ha_core_memory ]]]' 
    supervisor1:
      card: 
        type: custom:button-card 
        template: HA资源信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          name: CPU
          entity: '[[[ return variables.ha_supervisor_cpu ]]]' 
    supervisor2:
      card: 
        type: custom:button-card 
        template: HA资源信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          name: 内存
          entity: '[[[ return variables.ha_supervisor_memory ]]]' 
    node_red1:
      card: 
        type: custom:button-card 
        template: HA资源信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          name: CPU
          entity: '[[[ return variables.node_red_cpu ]]]' 
    node_red2:
      card: 
        type: custom:button-card 
        template: HA资源信息样式模板1
        variables:
          主题: '[[[ return variables.主题 ]]]'
          name: 内存
          entity: '[[[ return variables.node_red_memory ]]]' 
    desk1:
      card: 
        type: custom:button-card 
        template: HA资源信息样式模板2
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity: '[[[ return variables.ha_host_disk_free ]]]' 
    desk2:
      card: 
        type: custom:button-card 
        template: HA资源信息样式模板3
        variables:
          主题: '[[[ return variables.主题 ]]]'
          entity_free: '[[[ return variables.ha_host_disk_free ]]]' 
          entity_used: '[[[ return variables.ha_host_disk_used ]]]' 
          entity_total: '[[[ return variables.ha_host_disk_total ]]]' 

HA资源信息样式模板1:
  layout: name_state
  show_icon: false
  show_label: true
  show_state: true
  name: '[[[ return variables.name ]]]'
  state_display: |
    [[[
        return states[variables.entity].state + "%";
    ]]]
  styles: 
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 0
      - background: rgb(0,0,0,0)
      - height: 40px
    name: 
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
    state:
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
  custom_fields:
    back: >
      [[[
          var color = variables.主题 == "on" ? "rgb(100,100,100,0.3)" : "rgb(200,200,200,0.3)";
          return `
            <div style="
              position: absolute;
              top: 20%;
              left: 60%;
              height: 60%;
              width: 5%;
              background: ${color};
            "></div>
          `;
      ]]]
    progress: >
      [[[
          var percent = states[variables.entity].state;
          var color = `hsl(${100-percent}, 100%, 50% ,0.8)`;
          percent= percent*0.6;
          return `
            <div style="
              position: absolute;
              top: ${80 - percent}%;
              left: 60%;
              height: ${percent}%;
              width: 5%;
              background: ${color};
              transition: width 0.5s ease;
            "></div>
          `;
      ]]]
HA资源信息样式模板2:
  layout: name_state
  show_icon: false
  show_label: true
  show_state: true
  name: 空闲
  state_display: |
    [[[
        return states[variables.entity].state + " GB";
    ]]]
  styles: 
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 0
      - background: rgb(0,0,0,0)
      - height: 40px
    name: 
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
    state:
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
HA资源信息样式模板3:
  layout: name_state
  show_icon: false
  show_label: true
  show_state: true
  name: 已用
  state_display: |
    [[[
        var used = states[variables.entity_used].state;
        var total = states[variables.entity_total].state;
        return Math.round((used/total)*100)+"%";
    ]]]
  styles: 
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - border-width: 0
      - border-radius: 0
      - background: rgb(0,0,0,0)
      - height: 40px
    name: 
      - font-size: 15px 
      - text-align: left
      - width: 160px
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
    state:
      - font-size: 15px
      - text-align: left
      - width: 160px
      - color: '[[[ return variables.主题 == "on" ? "rgb(0,0,0)" : "rgb(255,255,255)"; ]]]'
  custom_fields:
    back: >
      [[[
          var color = variables.主题 == "on" ? "rgb(100,100,100,0.3)" : "rgb(200,200,200,0.3)";
          return `
            <div style="
              position: absolute;
              top: 20%;
              left: 60%;
              height: 60%;
              width: 5%;
              background: ${color};
            "></div>
          `;
      ]]]
    progress: > 
      [[[
          var used = states[variables.entity_used].state;
          var total = states[variables.entity_total].state;
          var percent = (used/total)*100;
          var color = `hsl(${100-percent}, 100%, 50% ,0.8)`;
          percent= percent*0.6;
          return `
            <div style="
              position: absolute;
              top: ${80 - percent}%;
              left: 60%;
              height: ${percent}%;
              width: 5%;
              background: ${color};
              transition: width 0.5s ease;
            "></div>
          `;
      ]]]