action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_none_pupup() ]]]'  ## 引用全局函数【theme_none_pupup()】style样式
    content:
      type: vertical-stack
      cards:    
        - type: custom:button-card
          template: 空气炸锅卡片
          variables:  
            空气炸锅:  |
              [[[
                var kongqizhaguo = states["sensor.chufang_kongqizhaguo"].state;
                if( kongqizhaguo=="烹饪中" || kongqizhaguo=="预约中") return "sensor.chufang_kongqizhaguo"; 
                return "none";
              ]]]
            ## [关机,待机,暂停,预约中,烹饪中,预热中,烹饪完成,预热完成,预热暂停,抽锅暂停]
            开始亨饪: text.careli_cn_426704626_maf03_start_cook_a_3_1  ## [食谱id(str),食谱名称(str),工作时间(int),工作温度(int),预约时间(int),食材量(int),预热开关(int)]
            停止亨饪: button.careli_cn_426704626_maf03_cancel_cooking_a_2_2
            暂停亨饪: button.careli_cn_426704626_maf03_pause_a_2_3
            继续亨饪: button.careli_cn_426704626_maf03_resume_cook_a_3_2
            工作时间: number.careli_cn_426704626_maf03_target_time_p_2_3
            工作温度: number.careli_cn_426704626_maf03_target_temperature_p_2_4
            剩余时间: sensor.careli_cn_426704626_maf03_left_time_p_2_5
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
        - type: custom:button-card
          template: 蒸煮锅卡片
          variables:  
            蒸煮锅:  |
              [[[
                var zhengzhuguo = states["sensor.chufang_zhengzhuguo"].state;
                if( zhengzhuguo =="烹饪中" || zhengzhuguo =="保温中" || zhengzhuguo =="预约中" ) return "sensor.chufang_zhengzhuguo"; 
                return "none";
              ]]]
            ## [休眠中,待机中,烹饪中,暂停中,预约中,烹饪完成,故障中,烹饪完成升温中,烹饪完成降温中]
            亨饪模式: select.deerma_cn_647227974_v3_mode_p_2_2  ## [火锅,蒸煮,煲汤,煮粥,煮面,保温]
            工作时间: number.deerma_cn_647227974_v3_target_time_p_2_9
            火力等级: number.deerma_cn_647227974_v3_heat_level_p_2_6
            开始亨饪: button.deerma_cn_647227974_v3_start_cook_a_2_1
            停止亨饪: button.deerma_cn_647227974_v3_cancel_cooking_a_2_2
            暂停亨饪: button.deerma_cn_647227974_v3_pause_a_2_3
            继续亨饪: button.deerma_cn_647227974_v3_continue_cook_a_4_6
            剩余时间: sensor.deerma_cn_647227974_v3_left_time_p_2_3
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
        - type: custom:button-card
          template: 电饭煲卡片
          variables:  
            电饭煲:  |
              [[[
                var dianfanbao  = states["sensor.chufang_dianfanbao"].state;
                if( dianfanbao  =="烹饪中" || dianfanbao  =="保温中" || dianfanbao  =="预约中" ) return "sensor.chufang_dianfanbao"; 
                return "none";
              ]]]
            ## [待机中,烹饪中,保温中,预约中]
            开始亨饪: text.chunmi_cn_119441120_normal3_start_cook_a_2_1  ## [烹饪模式(int)][1:精煮饭、2:快煮饭、3:煮粥、4:保温]
            停止亨饪: button.chunmi_cn_119441120_normal3_cancel_cooking_a_2_2
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
        - type: custom:button-card
          template: 电压力锅卡片
          variables: 
            电压力锅:  |
              [[[
                var dianyaliguo = states["sensor.chufang_dianyaliguo"].state;
                if( dianyaliguo =="烹饪中" || dianyaliguo =="保温中" || dianyaliguo =="预约中" ) return "sensor.chufang_dianyaliguo"; 
                return "none";
              ]]]
            ## [待机中,工作中,保温中,预约中,故障]
            开始亨饪: text.chunmi_cn_824782007_mini1_start_cook_a_2_1  ## [烹饪模式(int)][1:米饭、3:牛羊肉、4:鸡鸭肉、7:煲汤、9:开盖煮、10:保温]
            停止亨饪: button.chunmi_cn_824782007_mini1_cancel_cooking_a_2_2
            剩余时间: sensor.chunmi_cn_824782007_mini1_left_time_p_2_5
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
        - type: custom:button-card
          template: 破壁机卡片
          variables:    
            破壁机:  |
              [[[
                var pobiji = states["sensor.chufang_pobiji"].state;
                if( pobiji=="Busy" || pobiji=="Keep Warm") return "sensor.chufang_pobiji"; 
                return "none";
              ]]] 
            ## [Idle,Busy,Paused,Delay,Sleep,Keep Warm,Completed,Fault]
            开始亨饪: text.chunmi_cn_682421582_a1_start_cook_a_2_1  ## [烹饪模式(int)][1豆浆、2果蔬汁、3浓汤、4奶昔、5玉米汁、6保温]
            停止亨饪: button.chunmi_cn_682421582_a1_cancel_cooking_a_2_2
            剩余时间: sensor.chunmi_cn_682421582_a1_left_time_p_2_3
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
        - type: custom:button-card
          template: 油烟机卡片
          variables:    
            油烟机:  |
              [[[
                var youyanji = states["sensor.youyanji"].state;
                if( youyanji > 10 ) return "sensor.youyanji"; 
                return "none";
              ]]]   
            关闭: switch.youyanji
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
        - type: custom:button-card
          template: 洗碗机卡片
          variables:      
            洗碗机: |
              [[[
                if( states["switch.180319907614846_power"].state =="on" ) return "sensor.chufang_xiwanji"; 
                return "none";
              ]]] 
            电源开关: switch.180319907614846_power
            保管: switch.180319907614846_storage
            童锁: lock.180319907614846_child_lock
            剩余时间: sensor.180319907614846_time_remaining
            门状态: binary_sensor.180319907614846_door
            漂洗计状态: binary_sensor.haocai_xiwanji_piaoxiji
            洗碗盐状态: binary_sensor.haocai_xiwanji_xiwanyan
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]