action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_none_pupup() ]]]'  ## 引用全局函数【theme_none_pupup()】style样式
    content:
      type: vertical-stack
      cards:    
        - type: custom:button-card
          template: 洗衣机卡片                 
          variables: 
            洗衣机: '[[[if (states["select.xiyiji"].state=="正在拖地") return "select.xiyiji"; return "none" ]]]'
            洗衣程序: select.xiyiji_laundrycycle
            洗涤程序: sensor.xiyiji_cyclephase
            累计用水量: sensor.04fa8372e143_totalwaterused
            累计用电量: sensor.04fa8372e143_totalelectricityused
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]