action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style:  '[[[ return theme_none_pupup() ]]]'  ## 引用全局函数【theme_none_pupup()】style样式
    content:
      type: vertical-stack
      cards:    
        - type: custom:button-card
          template: 浴霸卡片
          variables: 
            浴霸总开关: switch.yuba_gongwei
            吹风: switch.yuba_gongwei_blow
            换气: switch.yuba_gongwei_vent
            取暖: switch.yuba_gongwei_heat1
            温度: sensor.wendu_yuba_gongwei 
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]
        - type: custom:button-card
          template: 浴霸卡片
          variables: 
            浴霸总开关: switch.yuba_zhuwei
            吹风: switch.yuba_zhuwei_blow
            换气: switch.yuba_zhuwei_vent
            取暖: switch.yuba_zhuwei_heat1
            温度: sensor.wendu_yuba_zhuwei 
            主题: '[[[ return theme() ]]]' ## 主题颜色[on]或[off]或[函数返回值]