地暖卡片:
  triggers_update:
    - '[[[ return variables.地暖 ?? ""]]]'
  styles:
    grid:
      - grid-template-areas: >
          [[[
              window.地暖颜色 = "rgb(254,111,33)";  
              if(variables.地暖 !="none"){
                  return `"背景 背景 背景 背景"
                          "名称 名称 状态 开关"
                          "图标 加减按钮 主按钮区域 主按钮区域"
                          "空白行 空白行 空白行 空白行"
                          "曲线图 曲线图 曲线图 曲线图"`
              } 
               if(variables.地暖 =="none"){
                  return `` 
              }
          ]]] 
      - grid-template-columns: 15% 26% 47% 12%
      - grid-template-rows: 0 0 0 12.5vw 12.5vw
    card: 
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 
      - height: |
          [[[ 
              if( variables.地暖 !="none") {
                return "calc(25vw + 8px);"
              } 
              else return "0";
          ]]]
      - display: |
          [[[
              if (variables.地暖 == "none") {
                  return "none";
              }
          ]]]
  custom_fields:
    背景:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 25vw
            - padding: 0
            - border-width: 0
            - border-radius: 0
            - cursor: none
            - --mdc-ripple-press-opacity: 
            - border-radius: 3vw
            - height: 25vw
            - background: | 
                [[[
                    var state = states[variables.地暖]?.state;
                    if( variables.主题=='off' && state =='auto')  return "linear-gradient(90deg, "+地暖颜色+" -50%, rgb(50,50,50) 50%)";
                    if( variables.主题=='on'  && state =='auto')  return "linear-gradient(90deg, "+地暖颜色+" -50%, rgb(255,255,255) 50%)";
                    if( variables.主题=='off' && state =='off') return "rgb(50,50,50)";
                    if( variables.主题=='on'  && state =='off') return "rgb(255,255,255)";
                    return variables.主题 == 'on' ? "rgb(255,255,255)" : "rgb(50,50,50)";
                ]]] 
    曲线图:
      card:
        type: custom:mini-graph-card
        tap_action:
          action: none
        hold_action:
          action: none
        line_width: 1
        hours_to_show: 24
        smoothing: true
        height: 50
        show:
          name: false
          icon: false
          state: false
          legend: false
          loading_indicator: false
        cache: true
        entities:
          - entity: '[[[ return variables.地暖 ?? "" ]]]'
            attribute: current_temperature
            color: '[[[ return 地暖颜色 ]]]'
    名称:
      card:
        type: custom:button-card
        show_label: true
        label: '[[[ return states[variables.地暖]?.attributes?.friendly_name ?? "名称"]]]'
        styles:
          card:
            - margin-top: 8.25vw
            - padding: 0
            - border-radius: 0
            - width: 50vw
            - margin-left: 2.5vw
            - border-width: 0
            - background: rgb(0,0,0,0)
          label:
            - justify-self: start
            - font-size: 4vw
            - font-weight: bold
            - color: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)"; ]]]'
    状态:
      card:
        type: custom:button-card
        label: |
          [[[ 
              var state = states[variables.地暖]?.state;
              var temp = states[variables.地暖]?.attributes.current_temperature ?? "-";
              if(state =='off')   return "关闭: "+ temp + "<font size='1px'><b>°C&ensp;</b></font>";
              if(state =='auto')  return "开启: "+ temp + "<font size='1px'><b>°C&ensp;</b></font>";
              return "离线";
          ]]]
        show_label: true
        styles: 
          card:
            - margin-top: 8.25vw
            - padding: 0
            - border-radius: 0
            - border-width: 0
            - background: rgb(0,0,0,0)
          label:
            - justify-self: start
            - font-size: 3vw
            - font-weight: bold
            - margin-top: 0.5vw
            - margin-left: 0vw
            - color: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)"; ]]]'
    开关:
      card:
        type: custom:button-card
        entity: '[[[ return  variables.地暖 ?? "" ]]]'
        tap_action:
          action: toggle
        show_name: false
        show_icon: true
        icon: |
          [[[ 
              var state = states[variables.地暖]?.state;      
              if( state =='auto')  return "mdi:toggle-switch";
              if( state =='off') return "mdi:toggle-switch-off";
              return "mdi:toggle-switch-off";
          ]]]
        styles:
          card:
            - margin-top: 8.25vw
            - cursor: none
            - --mdc-ripple-press-opacity: 0.2
            - padding: 0
            - border-radius: 2vw
            - width: 8vw
            - height: 
            - border-width: 0
            - background: rgb(0,0,0,0)
          icon:
            - width: 8vw
            - height: 8vw
            - color: |
                [[[
                    var state = states[variables.地暖]?.state;
                    if( state =='auto') return 地暖颜色;
                    return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)";
                ]]]
    图标:
      card:
        type: custom:button-card
        show_icon: true
        icon: |
          [[[ 
              var state = states[variables.地暖]?.state;      
              if( state =='auto') return "mdi:fan";
              if( state =='off')  return "mdi:fan-off";
              return "mdi:fan-off";
          ]]] 
        styles:
          card:
            - margin-top: 25vw
            - padding: 0
            - border-radius: 0
            - width: 20vw 
            - height: 20vw
            - margin-left: '-2vw'
            - border-width: 0
            - background: rgb(0,0,0,0)
          icon: 
            - color: |
                [[[
                    var state = states[variables.地暖]?.state;
                    if( state =='auto'  )  return 地暖颜色;
                    return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)";
                ]]]
            - animation: |
                [[[ 
                    var state = states[variables.地暖]?.state;     
                    if( state =='auto') return "rotating 1.5s linear infinite"; 
                    if( state =='off')  return "";
                    return "";     
                ]]]
    加减按钮:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 25vw
            - padding: 0 2vw 0 0
            - cursor: none
            - cursor: none 
            - border-width: 0
            - border-radius: 0
            - background: rgb(0,0,0,0)
          grid:
            - grid-template-areas: |
                "减 数值 加"
            - grid-template-rows: 100%
            - grid-auto-columns: minmax(0, 1fr)
            - grid-auto-flow: column
        custom_fields:
          数值:
            card:
              type: custom:button-card
              show_label: true
              label:  '[[[ return states[variables.地暖]?.attributes.temperature+"°";]]]'
              styles:
                card:
                  - padding: 0
                  - border-radius: 0
                  - width: 8vw
                  - height: 6vw
                  - margin-left: 0vw
                  - border-width: 0
                  - background: rgb(0,0,0,0)
                label:
                  - font-size: 3.5vw
                  - font-weight: bold
                  - color: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)"; ]]]'
          减:
            card:
              type: custom:button-card
              show_icon: true
              icon: mdi:minus
              styles:
                icon:
                  - width: 6vw
                  - height: 6vw
                  - color: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)"; ]]]'
                card:
                  - cursor: none
                  - --mdc-ripple-press-opacity: 0.2
                  - padding: 0
                  - border-radius: 2vw
                  - width: 8vw
                  - height: 6vw
                  - border-width: 0
                  - background: rgb(0,0,0,0)
              tap_action:
                action: call-service
                service: climate.set_temperature
                data:
                  temperature: ' [[[ return states[variables.地暖]?.attributes?.temperature-1 ]]]'
                target:
                  entity_id: '[[[ return  variables.地暖 ?? "" ]]]'
          加:
            card:
              type: custom:button-card
              show_icon: true
              icon: '[[[ return "mdi:plus"]]]'
              styles:
                icon:
                  - width: 6vw
                  - height: 6vw
                  - color: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)"; ]]]'
                card:
                  - cursor: none
                  - --mdc-ripple-press-opacity: 0.2
                  - padding: 0
                  - border-radius: 2vw
                  - width: 8vw
                  - height: 6vw
                  - border-width: 0
                  - background: rgb(0,0,0,0)
              tap_action:
                action: call-service
                service: climate.set_temperature
                data:
                  temperature: ' [[[ return states[variables.地暖]?.attributes?.temperature-(-1) ]]]'
                target:
                  entity_id: '[[[ return  variables.地暖 ?? "" ]]]'    
    主按钮区域:
      card:
        type: custom:button-card 
        tap_action:
          action: none
        hold_action:
          action: none
        styles:
          grid:
            - grid-template-areas: |
                "dinuan1 dinuan2 dinuan3"
            - grid-template-rows: 100%
            - grid-auto-columns: minmax(0, 1fr)
            - grid-auto-flow: column
          card:
            - margin-top: 25vw
            - cursor: none  
            - width: 52vw
            - padding: 0 
            - border-radius: 0
            - border-width: 0
            - background: rgb(0,0,0,0)
        custom_fields:
          dinuan1:
            card:
              type: custom:button-card
              icon: mdi:snowflake-alert 
              name: 防冻
              template: 地暖主按钮样式
              variables:
                地暖: '[[[ return variables.地暖 ?? "" ]]]'
                主题: '[[[ return variables.主题 ?? ""]]]'
                preset_mode: 15
          dinuan2:
            card:
              type: custom:button-card
              icon: mdi:thermostat-auto 
              name: 舒适
              template: 地暖主按钮样式
              variables:
                地暖: '[[[ return variables.地暖 ?? "" ]]]'
                主题: '[[[ return variables.主题 ?? ""]]]'
                preset_mode: 13
          dinuan3:
            card:
              type: custom:button-card
              icon: mdi:calendar-week 
              name: 周计划
              template: 地暖主按钮样式
              variables:
                地暖: '[[[ return variables.地暖 ?? "" ]]]'
                主题: '[[[ return variables.主题 ?? ""]]]'
                preset_mode: 14

地暖主按钮样式:
  triggers_update:
    - '[[[ return variables.地暖 ?? "" ]]]'
  layout: icon_name
  show_icon: true
  show_name: true
  styles:
    card:
      - cursor: none
      - --mdc-ripple-press-opacity: 0.2
      - width: 14.6vw
      - height: 6vw
      - border-radius: 1.5vw 
      - background: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(120,120,120)"; ]]]'
    name:
      - color: rgb(255,255,255)
      - font-size: 1.1vh
      - margin-left: -2vw
      - font-weight: bold
    icon:
      - width: 4vw 
      - height: 4vw
      - margin-left: 2vw
      - color: |
          [[[
              var state = states[variables.地暖]?.state;
              var mode= states[variables.地暖]?.attributes?.preset_mode;
              if( state =='on' && mode == variables.preset_mode) return 地暖颜色;          
              return "rgb(255,255,255)"; 
          ]]] 
  tap_action:
    action: call-service
    service: climate.set_preset_mode
    data:
      preset_mode: '[[[ return  variables.preset_mode ]]]'
    target:
      entity_id: '[[[ return  variables.地暖 ?? "" ]]]'
