UI表头_HA:   
  triggers_update: all
  layout: icon_state
  show_icon: true  
  show_state: true 
  icon: mdi:home-assistant        
  state_display: | 
    [[[
        var sum = Object.values(hass.states).filter(
          entity => entity.entity_id.startsWith("update.") && entity.state === "on"
        ).length;
        if(sum > 0) return '<font color="#FF0A0A"><b>HA:'+sum+'</b></font>';
        if(sum ==0) return 'HA:0';
    ]]]
  styles:
    icon:
      - width: 3.8vw
      - height: 2vh
      - margin-left: 1vw
      - color: '[[[ return theme_color(0,255,0.9) ]]]' 
    state:
      - margin-left: -2vw 
      - font-size: 1.3vh
      - color: '[[[ return theme_color(0,255,0.9) ]]]' 
    card:
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - padding: 0
      - background: '[[[ return theme_color(255,50,0.5) ]]]' 
      - border: '[[[ return theme_border(0,255,0.15) ]]]'
      - border-radius: 4vw
      - width: 16vw
      - height: 2.8vh
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        style: '[[[ return theme_none(); ]]]'
        content:
          type: vertical-stack
          cards:
            - type: custom:button-card
              template: HA版本信息卡片    
              variables:
                operating_system: '[[[ return variables.operating_system ]]]'
                ha_core: '[[[ return variables.ha_core ]]]'
                ha_supervisor: '[[[ return variables.ha_supervisor ]]]'
                node_red: '[[[ return variables.node_red ]]]'
                主题: '[[[ return theme() ]]]'
            - type: custom:button-card
              template: HA资源信息卡片    
              variables:
                ha_core_cpu: '[[[ return variables.ha_core_cpu ]]]'
                ha_core_memory: '[[[ return variables.ha_core_memory ]]]'
                ha_supervisor_cpu: '[[[ return variables.ha_supervisor_cpu ]]]'
                ha_supervisor_memory: '[[[ return variables.ha_supervisor_memory ]]]'
                node_red_cpu: '[[[ return variables.node_red_cpu ]]]'
                node_red_memory: '[[[ return variables.node_red_memory ]]]'
                ha_host_disk_free: '[[[ return variables.ha_host_disk_free ]]]'
                ha_host_disk_used: '[[[ return variables.ha_host_disk_used ]]]'
                ha_host_disk_total: '[[[ return variables.ha_host_disk_total ]]]'
                主题: '[[[ return theme() ]]]'
            - type: custom:button-card
              template: HA备份信息卡片    
              variables:
                backup_last: '[[[ return variables.backup_last ]]]'
                backup_next: '[[[ return variables.backup_next ]]]'
                主题: '[[[ return theme() ]]]'
            - type: custom:button-card
              template: HA更新信息卡片    
              variables:
                主题: '[[[ return theme() ]]]'
            - type: custom:button-card
              template: HA离线信息卡片    
              variables:
                主题: '[[[ return theme() ]]]'

