UI表头_待办:        
  triggers_update:       
    - '[[[ return number1 ?? ""]]]'  
    - '[[[ return number2 ?? ""]]]'
    - '[[[ return switch1 ?? ""]]]'     
    - '[[[ return switch2 ?? ""]]]'     
    - '[[[ return variables.待办清单实体 ]]]'
    - '[[[ return variables.待办清单NR实体 ]]]'
    - '[[[ return variables.待办清单名称 ]]]'
    - '[[[ return variables.待办清单描述 ]]]'
    - '[[[ return variables.待办清单时间 ]]]'
  numeric_precision: 1
  layout: icon_state
  show_state: true
  show_name: false
  icon: mdi:clipboard-list  
  state_display: '[[[  return "待办:"+states[variables.待办清单实体]?.state ?? "0" ]]]'
  styles:
    icon: 
      - width: 3.8vw
      - height: 2vh
      - margin-left: 1vw
      - color: '[[[ return theme_color(0,255,0.9) ]]]' 
    state:
      - font-size: 1.25vh
      - width: 10vw
      - margin-left: -1.5vw
      - text-align: center
      - color: '[[[ return theme_color(0,255,0.9) ]]]' 
    card:
      - cursor: none
      - --mdc-ripple-press-opacity: 0.2  
      - padding: 0
      - background: '[[[ return theme_color(255,50,0.5) ]]]' 
      - border: '[[[ return theme_border(0,255,0.15) ]]]'
      - border-radius: 4vw
      - width: 16vw
      - height: 2.8vh
  tap_action: 
    action: fire-dom-event 
    browser_mod:
      service: browser_mod.popup
      data:
        style: '[[[ return theme_none(410); ]]]'
        content: 
          type: custom:button-card    
          template: 待办事项
          variables: 
            待办清单实体: '[[[ return variables.待办清单实体 ]]]'
            待办清单NR实体: '[[[ return variables.待办清单NR实体 ]]]'
            待办清单名称: '[[[ return variables.待办清单名称 ]]]'
            待办清单描述: '[[[ return variables.待办清单描述 ]]]'
            待办清单时间: '[[[ return variables.待办清单时间 ]]]'
            主题: '[[[ return variables.主题 ]]]'