
净水器:
  triggers_update:
    - '[[[ return variables.出水水质 ]]]'
    - '[[[ return variables.入水水质 ]]]'
    - '[[[ return variables.温度 ]]]'
    - '[[[ return variables.三合一滤芯 ]]]'
    - '[[[ return variables.RO滤芯 ]]]'
  styles:
    grid:
      - grid-template-areas: |
          'back' 
          'back1' 
          'back2' 
          'button_back1' 
          'button_back2' 
          'name' 
          'label' 
          'tdsout'
          'unit' 
          'button1' 
          'button2' 
      - grid-template-columns: 240px
      - grid-template-rows: 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px 0px
    card:
      - padding: 0
      - width: 240px
      - height: 340px
      - border-width: 0
      - background: transparent
  custom_fields:
    back:
      card:
        type: custom:button-card
        styles: 
          card:
            - margin-top: 340px
            - width: 240px
            - height: 340px
            - border-radius: 15px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(255,255,255)" : "rgb(50,50,50)" ]]]'
    back1:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 360px
            - border-width: 0
            - background: |
                [[[
                    var tds =  states[variables.出水水质].state;
                    if (tds>= 0 & tds<20) return "rgb(0,255,255)" ;
                    if (tds>=20 & tds<30) return "rgb(127,255,212)" ;
                    if (tds>=30 & tds<50) return "rgb(255,140,0)" ;
                    if (tds>=50 & tds<80) return "rgb(255,48,48)" ;
                    if (tds>=80 ) return "rgb(139,26,26)" ;
                ]]]
            - width: 240px
            - height: 240px
            - margin-left: 34px
            - clip-path: >-
                path('M157.4,85.3c0-1.3,0.1-2.5,0-3.7c-0.1-2-0.3-3.9-0.6-5.8c-0.4-3.1-1.1-6.2-1.8-9.2c-0.8-3-1.8-6-3-8.8
                c-1.7-4.1-3.7-8.1-6.2-11.8c-1.8-2.8-3.8-5.5-6-7.9c-1.5-1.8-3.1-3.4-4.8-5.1c-3.8-3.6-7.9-6.8-12.4-9.5s-9.2-4.9-14.2-6.6
                c-3.7-1.2-7.3-2.1-11.1-2.8c-1.7-0.3-3.4-0.5-5.1-0.7c-0.7-0.1-1.5-0.1-2.2-0.1c-2.2-0.1-4.6-0.4-6.8-0.1c-2.3,0.1-4.7,0.3-7,0.6
                c-5.1,0.6-10,1.8-14.8,3.4c-6.3,2.2-12.2,5.3-17.8,9.1c-2.2,1.5-4.4,3.2-6.5,5.1c-1.9,1.7-3.7,3.4-5.3,5.3c-3,3.4-5.8,7.2-8.2,11.2
                c-1.1,1.8-2.1,3.6-3,5.4c-2.6,5.3-4.6,10.9-5.8,16.7c-0.6,2.6-1,5.3-1.3,7.9c-0.1,1.5-0.2,3.2-0.4,4.7c-0.1,1.1-0.1,2.2-0.1,3.4
                c0.1,2.3,0.2,4.6,0.4,7c0.4,4.1,1.2,8,2.2,11.9c0.8,2.9,1.8,5.8,3,8.7c2,4.8,4.5,9.3,7.4,13.5c1.3,2,2.8,3.9,4.4,5.6
                c1.2,1.4,2.5,2.7,3.7,4c1.2,1.3,1.8,2.8,1.8,4.6c-0.1,3.5-2.9,6.2-5.9,6.4c-2,0.1-3.8-0.5-5.3-2c-4.2-4.2-7.9-8.8-11.2-13.8
                c-2.3-3.7-4.4-7.4-6.2-11.4c-1.4-3.1-2.6-6.2-3.7-9.5c-1.1-3.5-2-7.1-2.6-10.7c-0.4-2.3-0.7-4.6-0.9-6.9c-0.1-1.8-0.4-3.6-0.3-5.4
                c0-0.7-0.1-1.5-0.1-2.2c0.1-2,0.1-4.1,0.2-6.1C0.3,78,0.5,76.6,0.6,75c0.2-1.8,0.5-3.4,0.8-5.2c0.7-4,1.8-7.9,3-11.7
                c1-3,2.2-5.9,3.5-8.8c2-4.4,4.4-8.5,7.1-12.5c1.9-2.8,4-5.5,6.3-8c1.4-1.5,2.8-3.1,4.3-4.6c2-1.9,3.9-3.7,6-5.3
                c2.1-1.8,4.4-3.4,6.6-4.8c3.4-2.2,7-4.3,10.8-6c3.2-1.5,6.3-2.7,9.6-3.9c3.1-1,6.2-1.8,9.3-2.5c2.6-0.5,5.2-0.9,7.8-1.2
                S81,0.2,83.6,0c2-0.1,4.1,0.1,6.1,0.1c1.5,0,3.1,0.2,4.6,0.4c2.6,0.3,5.1,0.7,7.7,1.2c1.6,0.3,3.2,0.7,4.8,1.1
                c2.6,0.7,5.1,1.5,7.6,2.4c2.9,1.1,5.7,2.2,8.4,3.7c4.2,2,8.2,4.5,12,7.2c2,1.5,4,3.1,6,4.7c2.5,2,4.6,4.4,6.9,6.6
                c1.4,1.5,2.7,3,3.9,4.6c1.8,2.2,3.4,4.5,4.9,6.8c1.1,1.8,2.2,3.5,3.2,5.3c2.3,4.3,4.3,8.7,5.9,13.3c1.2,3.4,2.2,6.8,2.9,10.3
                c0.5,2.5,0.9,4.9,1.2,7.4c0.2,1.9,0.4,3.7,0.5,5.6c0.1,2.6,0.1,5.2,0.1,7.8c-0.1,2.2-0.3,4.5-0.6,6.7c-0.4,3.6-1.1,7.2-2,10.7
                c-0.9,3.7-2.1,7.2-3.5,10.7c-0.8,2-1.6,3.9-2.5,5.8c-1.3,2.6-2.6,5.1-4.1,7.5c-1.5,2.5-3.2,5-5.1,7.3c-1.1,1.4-2.2,2.8-3.4,4.1
                c-1.2,1.4-2.5,2.7-3.7,4c-2.2,2.2-5.7,2.5-8.3,0.8c-3.3-2.2-3.7-6.8-1.2-9.6c0.6-0.6,1.1-1.2,1.7-1.8c2.6-2.7,4.9-5.6,7.1-8.7
                c2.2-3.2,4.1-6.5,5.8-10c2.4-5.1,4.1-10.3,5.3-15.7c0.5-2.2,0.8-4.5,1.1-6.8c0.1-1.4,0.3-2.7,0.4-4.1
                C157.4,88.1,157.4,86.7,157.4,85.3L157.4,85.3z')
    back2:
      card:
        type: custom:button-card
        styles: 
          card:
            - margin-top: 300px
            - margin-left: 30px
            - border-width: 0
            - background: |
                [[[ 
                    var tds =  states[variables.出水水质].state;
                    if (tds>= 0 & tds<20) return "radial-gradient(rgb(0,255,255,0.3) 20%, transparent 50%)" ;
                    if (tds>=20 & tds<30) return "radial-gradient(rgb(127,255,212,0.3) 20%, transparent 50%)" ;
                    if (tds>=30 & tds<50) return "radial-gradient(rgb(255,140,0,0.3) 20%, transparent 50%)" ;
                    if (tds>=50 & tds<80) return "radial-gradient(rgb(255,48,48,0.3) 20%, transparent 50%)" ;
                    if (tds>=80 ) return "radial-gradient(rgb(139,26,26,0.3) 20%, transparent 50%)" ;
                ]]]
            - width: 180px
            - height: 180px
    button_back1:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 515px
            - margin-left: 20px
            - width: 200px 
            - height: 35px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'
            - border-radius: 10px
    button_back2:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 605px
            - margin-left: 20px
            - width: 200px 
            - height: 35px
            - border-width: 0
            - background: '[[[ return variables.主题 =="on" ? "rgb(230,230,230)" : "rgb(80,80,80)" ]]]'
            - border-radius: 10px
    name:
      card:
        type: custom:button-card
        label: 净水器
        show_label: true
        styles:
          card:
            - margin-top: 65px
            - border-width: 0
            - background: transparent
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 19px
    label:
      card:
        type: custom:button-card
        label: |
          [[[ 
              var tds =  states[variables.出水水质].state;
              if (tds> 0 & tds<20) return "优秀";
              if (tds>=20 & tds<30) return "良好";
              if (tds>=30 & tds<50) return "一般";
              if (tds>=50 & tds<80) return "较差";
              if (tds>=80 ) return "极差";
          ]]]
        show_label: true
        styles:
          card:
            - margin-top: 200px
            - border-width: 0
            - background: transparent
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 13px
    tdsout:
      card:
        type: custom:button-card
        label: '[[[ return states[variables.出水水质].state ]]]'
        show_label: true
        styles:
          card:
            - margin-top: 300px
            - border-width: 0
            - background: transparent
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 60px
    unit:
      card:
        type: custom:button-card
        label: tds
        show_label: true
        styles:
          card:
            - margin-top: 380px
            - border-width: 0
            - background: transparent
          label:
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'
            - font-size: 13px
    button1:
      card:
        type: custom:button-card
        show_label: true 
        label: |
          [[[
              var lvxin =  states[variables.三合一滤芯].state/24+"天 ";
              var lvxin0 =  Math.round(states[variables.三合一滤芯].state /86.40)+"%";
              return "三合一滤芯 已用: "+lvxin+lvxin0;
          ]]]
        styles:  
          card:
            - padding: 0
            - margin-top: 515px
            - margin-left: 20px
            - width: 200px
            - height: 35px 
            - border-radius: 10px
            - border-width: 0
            - background: transparent
          label:
            - font-size: 11px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'  
    button2:
      card:
        type: custom:button-card
        show_label: true 
        label: |
          [[[
              var lvxin =  states[variables.三合一滤芯].state/24+"天 ";
              var lvxin0 =  Math.round(states[variables.RO滤芯].state /172.80)+"%";
              return "RO反渗透滤芯 已用: "+lvxin+lvxin0;
          ]]]
        styles: 
          card:
            - padding: 0
            - margin-top: 605px
            - margin-left: 20px
            - width: 200px
            - height: 35px 
            - border-radius: 10px
            - border-width: 0
            - background: transparent
          label:
            - font-size: 11px
            - color: '[[[ return variables.主题 =="on" ? "rgb(0,0,0)" : "rgb(255,255,255)" ]]]'  
    