净水器卡片:
  triggers_update:
    - '[[[ return variables.出水水质 ?? ""]]]'
    - '[[[ return variables.进水水质 ?? ""]]]'
    - '[[[ return variables.温度 ?? ""]]]'
    - '[[[ return variables.三合一滤芯 ?? ""]]]'
    - '[[[ return variables.ro滤芯 ?? ""]]]'
  tap_action:
    action: none
  hold_action:
    action: none
  styles:
    grid:
      - grid-template-areas: >
          [[[
              window.净水器颜色 = "rgb(0,188,213)";  
              if(variables.entity !="none"){
                  return `"背景 背景 背景 背景"
                          "名称 名称 状态 开关"
                          "图标 空白区域 主按钮区域 主按钮区域"`
              } 
               if(variables.entity =="none"){
                  return `` 
              }  
          ]]]  
      - grid-template-columns: 13% 14% 61% 12%
      - grid-template-rows: 0 8vw 12vw
    card:
      - padding: 0
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - height: |
          [[[ 
              if( variables.entity !="none") {
                return "calc(20vw + 8px);"
              } 
              else return "0";
          ]]]
      - display: |
          [[[
              if (variables.entity == "none") {
                  return "none";
              }
          ]]]
  custom_fields:
    背景:
      card:
        type: custom:button-card
        styles:
          card:
            - margin-top: 20vw
            - padding: 0
            - border-width: 0
            - cursor: none
            - --mdc-ripple-press-opacity: 0
            - border-radius: 3vw
            - height: 20vw
            - background: |
                [[[
                    if( variables.主题=='on' )  return "linear-gradient(90deg, "+净水器颜色+" -50%,rgb(255,255,255) 50%)";
                    if( variables.主题=='off')  return "linear-gradient(90deg, "+净水器颜色+" -50%,rgb(50,50,50) 50%)";
                    return variables.主题 == "on" ? "rgb(255,255,255)" : "rgb(50,50,50)";
                ]]]
    开关:
      card:
        type: custom:button-card
        show_name: false
        show_icon: true
        icon: mdi:toggle-switch
        styles:
          card:
            - cursor: none
            - --mdc-ripple-press-opacity: 0.2
            - padding: 0
            - border-radius: 2vw
            - width: 8vw
            - height: 8vw
            - border-width: 0
            - background: transparent
          icon:
            - width: 8vw
            - height: 8vw  
            - color: '[[[ return 净水器颜色]]]'
    图标:
      card:
        type: custom:button-card
        show_icon: true
        icon: mdi:fan
        styles:
          card:
            - padding: 0
            - border-radius: 0
            - width: 20vw 
            - height: 20vw
            - margin-left: '-2vw'
            - border-width: 0
            - background: transparent
          icon: 
            - color: '[[[ return 净水器颜色]]]'
            - animation: rotating 1.5s linear infinite
    名称:
      card:
        type: custom:button-card
        show_label: true
        label: 净水器
        styles:
          card:
            - padding: 0
            - border-radius: 0
            - width: 50vw
            - margin-left: 2.5vw
            - border-width: 0
            - background: transparent
          label:
            - justify-self: start
            - font-size: 4vw
            - font-weight: bold
            - color: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)"; ]]]'
    状态:  
      card:
        type: custom:button-card
        label: |
          [[[ 
              var tdsout = states[variables.出水水质]?.state;
              var temp = states[variables.温度]?.state;
              return "出水水质: "+tdsout+"TDS 温度: "+temp+"℃";
          ]]]
        show_label: true
        styles: 
          card:
            - padding: 0 
            - border-radius: 0
            - border-width: 0
            - background: transparent
          label:
            - justify-self: start
            - font-size: 3vw
            - font-weight: bold
            - margin-top: 0.5vw
            - color: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(255,255,255)"; ]]]'           
    主按钮区域:
      card:
        type: custom:button-card
        tap_action:
          action: none
        hold_action:
          action: none
        styles:
          grid:
            - grid-template-areas: |
                'b1 b2 b3 b4 b5' 
            - grid-template-columns: 20% 20% 20% 20% 20% 
            - grid-template-rows: 100%
          card:
            - cursor: none  
            - width: 66vw
            - padding: 0
            - border-radius: 0
            - border-width: 0
            - background: transparent
        custom_fields:
          b1:
            card:
              type: custom:button-card
              template: 净水器按钮样式模板
              icon: mdi:water
              name: '[[[ return "入: "+states[variables.进水水质]?.state ]]]'
              variables:
                主题: '[[[ return variables.主题 ?? ""]]]'
          b2:
            card:
              type: custom:button-card
              template: 净水器按钮样式模板
              icon: mdi:water
              name: '[[[ return "出: "+states[variables.出水水质]?.state ]]]'
              variables:
                主题: '[[[ return variables.主题 ?? ""]]]'
          b3:
            card:
              type: custom:button-card
              template: 净水器按钮样式模板
              icon: mdi:thermometer
              name: '[[[ return states[variables.温度]?.state+"℃" ]]]'
              variables:
                主题: '[[[ return variables.主题 ?? ""]]]'
          b4:
            card:
              type: custom:button-card
              template: 净水器按钮样式模板
              show_icon: false
              show_name: false
              show_label: true
              label: |
                [[[ 
                    var lvxin1 =  Math.round(states[variables.三合一滤芯]?.state /86.40)+"%";
                    return "3in1: "+lvxin1
                ]]]
              variables:
                主题: '[[[ return variables.主题 ?? ""]]]'
          b5:
            card:
              type: custom:button-card
              template: 净水器按钮样式模板
              show_icon: false
              show_name: false
              show_label: true
              label: |
                [[[ 
                    var lvxin2 =  Math.round(states[variables.ro滤芯]?.state /172.80)+"%";
                    return "RO: "+lvxin2
                ]]]
              variables:
                主题: '[[[ return variables.主题 ?? ""]]]'
  
净水器按钮样式模板:
  triggers_update:
    - '[[[ return variables.出水水质 ?? ""]]]'
    - '[[[ return variables.进水水质 ?? ""]]]'
    - '[[[ return variables.温度 ?? ""]]]'
    - '[[[ return variables.三合一滤芯 ?? ""]]]'
    - '[[[ return variables.ro滤芯 ?? ""]]]'
  layout: icon_name
  show_icon: true 
  show_name: true 
  styles: 
    card:
      - cursor: none
      - --mdc-ripple-press-opacity: 0.2
      - width: 12.2vw
      - height: 6vw
      - border-radius: 1.5vw 
      - background: '[[[ return variables.主题 == "on" ? "rgb(50,50,50)" : "rgb(120,120,120)"; ]]]'
    name:
      - color: rgb(255,255,255)
      - font-size: 1vh
      - margin-left: -4vw
      - font-weight: bold
    label:
      - color: rgb(255,255,255)
      - font-size: 1vh
      - margin-top: -5vw
      - margin-left: 0vw
      - font-weight: bold
    icon:
      - width: 3vw
      - height: 3vw
      - margin-left: 0vw
      - color: rgb(255,255,255)

